<a href="https://colab.research.google.com/github/nilsberzins/stat-405-final/blob/main/EDA405.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Connect to Database and pull data

In [1]:
!pip install pymysql
!pip install boto3
!pip install sqlalchemy
!pip install python-dotenv

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 1.3 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1
Collecting boto3
  Downloading boto3-1.38.25-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<1.39.0,>=1.38.25 (from boto3)
  Downloading botocore-1.38.25-py3-none-any.whl.metadata (5.7 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3)
  Downloading jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.14.0,>=0.13.0 (from boto3)
  Downloading s3transfer-0.13.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.11/dist-packages (from botocore<1.39.0,>=1.38.25->boto3) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.11/dist-packages (from botocore<1.39.0,>=1.38.25->boto3) (2.4.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.39.0,>=1.38.25->boto3) (1.17.0)
Downloading boto3-1.38.25-py3-none-any.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.9/139.9 kB 9.1 MB/s eta 0:00:00
Downloading botocore-1.38.25-py3-none-any.whl (13.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.6/13.6 MB 102.7 MB/s eta 0:00:00
Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Downloading s3transfer-0.13.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.2/85.2 kB 6.3 MB/s eta 0:00:00
Installing collected packages: jmespath, botocore, s3transfer, boto3
Successfully installed boto3-1.38.25 botocore-1.38.25 jmespath-1.0.1 s3transfer-0.13.0
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.11/dist-packages (2.0.41)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (3.2.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (4.13.2)
Collecting python-dotenv
  Downloading python_dotenv-1.1.0-py3-none-any.whl.metadata (24 kB)
Downloading python_dotenv-1.1.0-py3-none-any.whl (20 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-1.1.0

In [2]:
# package for env variables in google colab: https://pypi.org/project/colab-env/
!pip install colab-env -qU
import colab_env

  Preparing metadata (setup.py) ... done
  Building wheel for colab-env (setup.py) ... done
Mounted at /content/gdrive
Creating vars.env in your Google Drive!

In [3]:
from colab_env import envvar_handler # modify env variables in var.env file in google drive

In [4]:
import pymysql
import sys
import boto3
import os

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
connection = pymysql.connect(
    host=os.getenv("AWS_DATABASE_ENDPOINT"),
    user=os.getenv("AWS_USER"),
    port=int(os.getenv("AWS_PORT")),
    passwd=os.getenv("AWS_PASSWORD"),
    database=os.getenv("AWS_DBNAME")
)

In [8]:
with connection.cursor() as cursor:
    cursor.execute("SHOW TABLES")
    tables = cursor.fetchall()

# Print table names
for table in tables:
    print(table[0])

SuperBowl_coinTosses
UC_salaries_data
google_elev_68sites
iris_data

**EDA**

In [82]:
query = """
SELECT `year`, location, title, `regular.pay`
FROM   UC_salaries_data
WHERE  `year` BETWEEN 2010 AND 2014;
"""

full_data = pd.read_sql(query, con=connection)
full_data.head()

<ipython-input-82-4eb8440029e6>:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  full_data = pd.read_sql(query, con=connection)

   year    location                         title  regular.pay
0  2010  Santa Cruz   ASSISTANT PROFESSOR-ACAD YR     69999.96
1  2010    Berkeley   GRAD STDNT RES-FULL FEE REM      5369.42
2  2010    Berkeley    TEACHING ASSISTANT - GSHIP      4802.00
3  2010    Berkeley  GRAD STDNT RES- NO REMISSION      3409.01
4  2010    Berkeley   GRAD STDNT RES-FULL FEE REM     11673.90

In [83]:
full_data = full_data.dropna()

In [84]:
to_drop = ["San Francisco", "UCOP", "DANR", "Hastings", "Hastings College of Law"]
full_data = full_data[~full_data["location"].isin(to_drop)]

In [85]:
pattern = r"""(?ix)                     # (?i)=ignore-case  (?x)=verbose mode
    \b(?:                               # word-start, then one of…
        prof(?:essors?\b|\.?\b)         #  "professor" / "professors" / "prof" / "prof."
      | lect(?:urer?s?\b|\b)            #  "lecturer(s)" / "lect"
    )
"""

filtered = full_data[full_data['title'].str.contains(pattern, regex=True, na=False)]

In [86]:
filtered.head()

     year    location                        title  regular.pay
0    2010  Santa Cruz  ASSISTANT PROFESSOR-ACAD YR     69999.96
20   2010    Berkeley     LECTURER - ACADEMIC YEAR     25454.75
94   2010    Berkeley     LECTURER - ACADEMIC YEAR     29248.46
175  2010    Berkeley     LECTURER - ACADEMIC YEAR     27058.69
178  2010    Berkeley     LECTURER - ACADEMIC YEAR     28679.78

In [87]:
def title_assign(x):
    if "PROFL" in x or "PROFESSIONAL" in x:
        return "OTHER"
    elif "VST" in x and "ASST" in x:
        return "VST ASST"
    elif "VST" in x and "ASSOC" in x:
        return "VST ASSOC"
    elif "VST" in x:
        return "VST PROF"
    elif "ADJ" in x and "ASST" in x:
        return "ADJ ASST"
    elif ("ASOC" in x or "ASSOC" in x) and "ADJ" in x:
        return "ADJ ASOC"
    elif "ADJ" in x:
        return "ADJ PROF"
    elif ("ASST" in x or "ASSIST" in x) and "PROF" in x:
        return "ASST PROF"
    elif "ASSOC" in x and "PROF" in x:
        return "ASSOC PROF"
    elif "PROF" in x:
        return "PROF"
    elif "SR" in x and "LECT" in x:
        return "SR LECT"
    elif "LECT" in x:
        return "LECT"
    else:
        return "OTHER"

In [88]:
filtered['prof_rank'] = (
    filtered['title']
        .str.upper()
        .fillna('')
        .apply(title_assign)
)

filtered.head()

<ipython-input-88-1fef090e102a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['prof_rank'] = (

     year    location                        title  regular.pay  prof_rank
0    2010  Santa Cruz  ASSISTANT PROFESSOR-ACAD YR     69999.96  ASST PROF
20   2010    Berkeley     LECTURER - ACADEMIC YEAR     25454.75       LECT
94   2010    Berkeley     LECTURER - ACADEMIC YEAR     29248.46       LECT
175  2010    Berkeley     LECTURER - ACADEMIC YEAR     27058.69       LECT
178  2010    Berkeley     LECTURER - ACADEMIC YEAR     28679.78       LECT

In [90]:
avg_salary = (
    filtered
      .groupby(['prof_rank', 'location'], as_index=False)
      .agg(avg_gross_pay=('regular.pay', 'mean'))
)

avg_salary

   prof_rank       location  avg_gross_pay
0   ADJ ASOC       Berkeley   65036.339167
1   ADJ ASOC          Davis   63688.819687
2   ADJ ASOC         Irvine   80163.695111
3   ADJ ASOC    Los Angeles   68869.765430
4   ADJ ASOC      Riverside   45546.000000
..       ...            ...            ...
91  VST PROF         Merced       0.000000
92  VST PROF      Riverside   13480.000000
93  VST PROF      San Diego   22479.380247
94  VST PROF  Santa Barbara   22957.410476
95  VST PROF     Santa Cruz   13188.493333

[96 rows x 3 columns]