## Connect to Database and pull data

In [1]:
!pip install pymysql
!pip install boto3
!pip install sqlalchemy
!pip install python-dotenv

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 1.9 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1
Requirement already satisfied: boto3 in /Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages (1.21.32)
Requirement already satisfied: botocore<1.25.0,>=1.24.32 in /Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages (from boto3) (1.24.32)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages (from boto3) (0.10.0)
Requirement already satisfied: s3transfer<0.6.0,>=0.5.0 in /Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages (from boto3) (0.5.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages (from botocore<1.25.0,>=1.24.32->boto3) (2.8.2)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages (from botocore<1.25.0,>=1.24.32->boto3) (1.26.9)
Requirement already satisfied: six>=1.5 in /Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.25.0,>=1.24.32->boto3) (1.16.0)
Requirement already satisfied: sqlalchemy in /Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages (1.4.32)
Requirement already satisfied: greenlet!=0.4.17 in /Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages (from sqlalchemy) (1.1.1)
Collecting python-dotenv
  Downloading python_dotenv-1.1.0-py3-none-any.whl (20 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-1.1.0

In [2]:
# package for env variables in google colab: https://pypi.org/project/colab-env/
!pip install colab-env -qU
import colab_env

ImportError: colab-env only works in a Google Colab notebook

In [4]:
from colab_env import envvar_handler # modify env variables in var.env file in google drive

ImportError: colab-env only works in a Google Colab notebook

In [3]:
envvar_handler.add_env("AWS_DATABASE_ENDPOINT", "database-dm4ds.c384k0y2av79.us-west-1.rds.amazonaws.com")
envvar_handler.add_env("AWS_USER", "ROuser")
envvar_handler.add_env("AWS_PORT", "3306")
envvar_handler.add_env("AWS_PASSWORD", "adsd3d3dfxds!@@QAS")
envvar_handler.add_env("AWS_DBNAME", "myDB")

NameError: name 'envvar_handler' is not defined

In [19]:
import pymysql
import sys
import boto3
import os

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [5]:
MAS405_AWS_MY_DB_ROUSER_PW='adsd3d3dfxds!@@QAS'
MAS405_AWS_MY_DB_ROUSER_HOST='database-dm4ds.c384k0y2av79.us-west-1.rds.amazonaws.com'
MAS405_AWS_MY_DB_ROUSER_USER='ROuser'
MAS405_AWS_MY_DB_ROUSER_DBNAME='myDB'
MAS405_AWS_MY_DB_ROUSER_PORT=3306

In [8]:
connection = pymysql.connect(
    host=MAS405_AWS_MY_DB_ROUSER_HOST,
    user=MAS405_AWS_MY_DB_ROUSER_USER,
    port=MAS405_AWS_MY_DB_ROUSER_PORT,
    passwd=MAS405_AWS_MY_DB_ROUSER_PW,
    database=MAS405_AWS_MY_DB_ROUSER_DBNAME
)

In [47]:
with connection.cursor() as cursor:
    cursor.execute("SHOW TABLES")
    tables = cursor.fetchall()

# Print table names
for table in tables:
    print(table[0])

SuperBowl_coinTosses
UC_salaries_data
google_elev_68sites
iris_data

In [ ]:
# from sqlalchemy import select
# stmt = select(user_table).where(user_table.c.name == "spongebob")
# print(stmt)

In [86]:
# years: 2010-2014
# 3024476 rows
# features: row_names	id	year	location	first.name	last.name	title	gross.pay	regular.pay	overtime.pay	other.pay
# location: DIVISION OF AGRICULTURE AND NATURAL RESOURCES (DANR)
# UCOP: university california office of the president
avg_loc_pay_df = pd.read_sql("SELECT location, AVG(`gross.pay`) FROM UC_salaries_data GROUP BY location", con=connection)
avg_loc_pay_df

<ipython-input-86-f645626e0120>:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  avg_loc_pay_df = pd.read_sql("SELECT location, AVG(`gross.pay`) FROM UC_salaries_data GROUP BY location", con=connection)

                   location  AVG(`gross.pay`)
0                Santa Cruz      26480.185848
1                  Berkeley      33418.287407
2                      DANR      34808.033162
3                     Davis      48795.614970
4                    Irvine      44389.647911
5               Los Angeles      51069.148947
6                    Merced      28558.416354
7                 Riverside      29015.387886
8                 San Diego      48018.481947
9             San Francisco      82919.020569
10            Santa Barbara      27167.823724
11                     UCOP      87482.700910
12                   ASUCLA       7729.955310
13  Hastings College Of Law      32675.792004
14                 Hastings      26595.393851

In [9]:
pd.read_sql("SELECT * FROM UC_salaries_data LIMIT 10", connection)

/Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,row_names,id,year,location,first.name,last.name,title,gross.pay,regular.pay,overtime.pay,other.pay
0,1,1,2010,Santa Cruz,*****,*****,ASSISTANT PROFESSOR-ACAD YR,74511.10,69999.96,0.0,4511.14
1,2,2,2010,Berkeley,***********,***********,GRAD STDNT RES-FULL FEE REM,5369.42,5369.42,0.0,0.00
2,3,3,2010,Berkeley,***********,***********,TEACHING ASSISTANT - GSHIP,4802.00,4802.00,0.0,0.00
3,4,4,2010,Berkeley,***********,***********,GRAD STDNT RES- NO REMISSION,3409.01,3409.01,0.0,0.00
4,5,5,2010,Berkeley,***********,***********,GRAD STDNT RES-FULL FEE REM,11673.90,11673.90,0.0,0.00
5,6,6,2010,Berkeley,***********,***********,ASSISTANT II,1712.44,1698.76,0.0,13.68
6,7,7,2010,Berkeley,***********,***********,ASSISTANT I,1325.50,1325.50,0.0,0.00
7,8,8,2010,Berkeley,***********,***********,GRAD STDNT RES-FULL FEE REM,6861.94,6861.94,0.0,0.00
8,9,9,2010,Berkeley,***********,***********,ASSISTANT I,1232.00,1232.00,0.0,0.00
9,10,10,2010,Berkeley,***********,***********,READER - GSHIP,11067.81,11067.81,0.0,0.00

In [44]:
df = pd.read_sql("SELECT * FROM UC_salaries_data", connection)
df.head()

/Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,row_names,id,year,location,first.name,last.name,title,gross.pay,regular.pay,overtime.pay,other.pay
0,1,1,2010,Santa Cruz,*****,*****,ASSISTANT PROFESSOR-ACAD YR,74511.10,69999.96,0.0,4511.14
1,2,2,2010,Berkeley,***********,***********,GRAD STDNT RES-FULL FEE REM,5369.42,5369.42,0.0,0.00
2,3,3,2010,Berkeley,***********,***********,TEACHING ASSISTANT - GSHIP,4802.00,4802.00,0.0,0.00
3,4,4,2010,Berkeley,***********,***********,GRAD STDNT RES- NO REMISSION,3409.01,3409.01,0.0,0.00
4,5,5,2010,Berkeley,***********,***********,GRAD STDNT RES-FULL FEE REM,11673.90,11673.90,0.0,0.00

In [45]:
df = df.dropna()
df

,row_names,id,year,location,first.name,last.name,title,gross.pay,regular.pay,overtime.pay,other.pay
0,1,1,2010,Santa Cruz,*****,*****,ASSISTANT PROFESSOR-ACAD YR,74511.10,69999.96,0.0,4511.14
1,2,2,2010,Berkeley,***********,***********,GRAD STDNT RES-FULL FEE REM,5369.42,5369.42,0.0,0.00
2,3,3,2010,Berkeley,***********,***********,TEACHING ASSISTANT - GSHIP,4802.00,4802.00,0.0,0.00
3,4,4,2010,Berkeley,***********,***********,GRAD STDNT RES- NO REMISSION,3409.01,3409.01,0.0,0.00
4,5,5,2010,Berkeley,***********,***********,GRAD STDNT RES-FULL FEE REM,11673.90,11673.90,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...
3024470,3024471,210097,2020,Riverside,BARA,MBOUP,MUSICIAN 2,4747.00,4747.00,0.0,0.00
3024471,3024472,210098,2020,Irvine,EPHANTUS,MBUGUA,REG RESP THER 1,38428.00,31437.00,713.0,6278.00
3024472,3024473,210099,2020,Los Angeles,PAULINE,MBUGUA,BLANK AST 2 PD,41089.00,39061.00,1953.0,75.00
3024473,3024474,210100,2020,Irvine,BERNADETTE,MBURU,PSYCHIATRIC TCHN SR,55677.00,52624.00,40.0,3013.00
3024474,3024475,210101,2020,Davis,PETER,MBUTHIA,MED CTR CUSTODIAN SR,38172.00,31671.00,1625.0,4876.00

In [57]:
pat = r'\bprof(?:essor\b|\.?\b)'
prof_rows = df[df['title'].str.contains(pat,case = False,na = False)]

In [24]:
titles = df["title"].unique().tolist()
titles = [i for i in titles if "PROF" in i]
titles

['ASSISTANT PROFESSOR-ACAD YR',
 'ACT PROFESSOR-LAW SCHOOL SCALE',
 'LIBRARY PROFESSIONAL 4',
 'ASSISTANT PROFESSOR-SFT-VM',
 'HS ASSISTANT CLIN PROF-HCOMP',
 'ASST PROF OF CLIN_____-HCOMP',
 'ASST PROF OF CLINICAL_____-FY',
 'HS ASST CLIN PROFESSOR-FY',
 'VST ASST PROFESSOR -FISCAL YR',
 'ASST CLINICAL PROFESSOR-VOL',
 'VISITING ASSISTANT PROF-HCOMP',
 'ASST PROF IN RESIDENCE - FY',
 'ASSISTANT PROF IN RES-HCOMP',
 'ASSISTANT ADJUNCT PROF-HCOMP',
 'ASST ADJUNCT PROF-MEDCOMP-A',
 'PROFESSOR - ACADEMIC YEAR',
 'ASSOCIATE PROF IN RES-HCOMP',
 'PROFESSOR-HCOMP',
 'ASST PROF-ACAD YR-BUS/ECON/ENG',
 'HS CLIN PROFESSOR-FISCAL YR',
 'PROFESSOR-ACAD YR-BUS/ECON/ENG',
 'ASSOC PROF OF CLIN_____-HCOMP',
 'PROFESSOR-ACAD YR-RECALLED',
 'HS ASSOCIATE CLIN PROF-HCOMP',
 'PROFESSOR-LAW SCHOOL SCALE',
 'PROFESSOR RECALLED-ACAD YR-1/9',
 'VIS ASST PROFESSOR-GENCOMP',
 'ASSOCIATE PROFESSOR-ACAD YR',
 'PROFESSOR OF CLINICAL___-HCOMP',
 'ASSOCIATE PROFESSOR-HCOMP',
 'ASSOCIATE ADJUNCT PROF-HCOMP',
 'ASSOC PROF-AY-BUS/ECON/ENG',
 'VST ASST PROFESSOR-ACAD YR-1/9',
 'PROFESSOR - FISCAL YR',
 'HS ASSOC CLIN PROFESSOR-FY',
 'HS CLINICAL PROFESSOR-HCOMP',
 'ASSOC PROF OF CLINICAL_____-FY',
 'PROFESSOR IN RESIDENCE-HCOMP',
 'PROFESSOR OF CLINICAL_____-FY',
 'HS ASST CLIN PROF-MEDCOMP-A',
 'PROFESSOR-GENCOMP-B',
 'PROFESSOR-FISCAL YR-RECALLED',
 'ASSISTANT PROFESSOR-HCOMP',
 'RESEARCH PROFESSOR',
 'VST ASST PROFESSOR-ACADEMIC YR',
 'ADJUNCT PROFESSOR-ACADEMIC YR',
 'ADJUNCT PROFESSOR - FISCAL YR',
 'PROFESSOR IN RESIDENCE - FY',
 'VISITING PROFESSOR-ACADEMIC YR',
 'VIS ASST PROFESSOR-MEDCOMP',
 'VSTG PROF-AY-1/9-BUS/ECON/ENGR',
 'ASSOC ADJUNCT PROFESSOR - AY',
 'PROFESSOR - FY -BUS/ECON/ENG',
 'ASSOC ADJUNCT PROFESSOR - FY',
 'ASSOC ADJUNCT PROF-GENCOMP-B',
 'HS ASSOC CLIN PROF-MEDCOMP-A',
 'ASST PROFESSOR - FISCAL YEAR',
 'HS CLIN PROF RECALLED-FY',
 'ASST ADJUNCT PROFESSOR - FY',
 'ADJUNCT PROFESSOR-HCOMP',
 'ATHLETICS PROFESSIONAL 1',
 'VISITING PROFESSOR-HCOMP',
 'ASSOCIATE PROFESSOR--SFT-VM',
 'ASST PROF IN RES-MEDCOMP-A',
 'ASST ADJUNCT PROFESSOR-ACAD YR',
 'PROFESSOR IN RESIDENCE-ACAD YR',
 'ATHLETICS PROFESSIONAL 2',
 'ASST ADJUNCT PROF-ACAD YR-1/9',
 'PROFESSOR EMERITUS (W/O SAL)',
 'TECHNICAL PROJECT MGT PROF"L 3',
 'ASST ADJ PROF-AY-BUS/ECON/ENG',
 'UNIVERSITY PROFESSOR',
 'PROFESSOR-MEDCOMP-A',
 'VST ASSOC PROFESSOR-AY-1/9TH',
 'VISITING ASSOCIATE PROF-HCOMP',
 'HS ASST CLIN PROFESSOR-ACAD YR',
 'ASSOC PROFESSOR - FISCAL YR',
 'HS ASSOC CLIN PROF-ACAD YR',
 'PROFESSOR-SFT-VM',
 'VST ASSOC PROFESSOR-ACAD YR',
 'VIS ASSOC PROFESSOR-GENCOMP',
 'REGENTS" PROFESSOR',
 'HS ASST CLIN PROF-FY-GENCOMP',
 'VISITING PROFESSOR - FISCAL YR',
 'VST PROFESSOR-ACAD YR-1/9 PMT',
 'ADJ PROF-ACAD YR-BUS/ECON/ENG',
 'PROF IN RES-MEDCOMP-A',
 'ASSOC PROFESSOR-AY-RECALLED',
 'VST ASSOC PROFESSOR-FISCAL YR',
 'CLINICAL PROFESSOR-VOLUNTEER',
 'ASST ADJ PROF-FY-BUS/ECON/ENG',
 'ASOC ADJUNCT PROF-GENCOMP-B',
 'ASSOC PROF-FY-BUS/ECON/ENG',
 'MGT AND PROF PROG (UNTITLED)',
 'AST PROF OF CLIN____-MEDCOMP-A',
 'ASST ADJUNCT PROF-GENCOMP-B',
 'TECHNICAL PROJECT MGT PROF"L 2',
 'ASST PROF IN RESIDENCE-ACAD YR',
 'ASSOC CLINICAL PROFESSOR-VOL',
 'HS CLINICAL PROFESSOR-ACAD YR',
 'ADJUNCT PROFESSOR-ACAD YR-1/9',
 'VST PROFESSOR-LAW SCHOOL SCALE',
 'TECHNICAL PROJECT MGT PROF"L 4',
 'PROFESSOR OF CLINICAL___',
 'ASSOC PROF IN RES-MEDCOMP-A',
 'ADJUNCT PROF-MEDCOMP-B',
 'PROF-AY-1/9-BUS/ECON/ENG-RECAL',
 'ASST PROF IN RES-GENCOMP-B',
 'ASSOC PROF IN RES-GENCOMP-B',
 'ASST ADJUNCT PROF-FY-GENCOMP',
 'PROF IN RES-GENCOMP-B',
 'ASO PROF OF CLIN___-MEDCOMP-A',
 'ASSOC PROF-RECALLED-AY-1/9TH',
 'PROF OF CLIN___-MEDCOMP-A',
 'HS CLIN PROF-MEDCOMP-A',
 'AST PROF OF CLIN___-MEDCOMP-A',
 'PROF IN RES-AY-BUS/ECON/ENG',
 'ASSOC ADJUNCT PROF-ACAD YR-1/9',
 'ACT ASST PROFESSOR-ACADEMIC YR',
 'CHIEF ADM & PROF SERVS OFFICER',
 'PROF-AY-BUS/ECON/ENG-RECALLED',
 'ADJ PROF-AY-1/9-BUS/ECON/ENG',
 'ASSOC PROF IN RESIDENCE-SFT-VM',
 'ASSISTANT PROFESSOR-FY-GENCOMP',
 'ASST PROF-FY-BUS/ECON/ENG',
 'ACT AST PROF-AY-BUS/ECON/ENG',
 'VIS ASSOC PROFESSOR-MEDCOMP',
 'ATHLETICS PROFESSIONAL 3',
 'AST PROF OF CLIN____-GENCOMP-A',
 'ASSISTANT PROFESSOR-AY-1/9TH',
 'ASSOC PROF IN RESIDENCE- FY',
 'ACT ASSOC PROFESSOR-ACAD YR',
 'ADJUNCT PROF-GENCOMP-B',
 'RES PROF-MILLER INST -ACAD YR',
 'ADJUNCT PROF-MEDCOMP-A',
 'ASST ADJUNCT PROF-MEDCOMP-B',
 'ASSOC PROFESSOR-FY-RECALL',
 'ASSO ADJ PROF-AY-BUS/ECON/ENG',
 'ASSOC ADJUNCT PROF-FY-GENCOMP',
 'PROFESSOR-AY-1/9-BUS/ECON/ENG',
 'ASSISTANT PROFESSOR-MEDCOMP-A',
 'ASST PROF-AY-1/9-BUS/ECON/ENG',
 'ASSOCIATE PROFESSOR-GENCOMP-B',
 'ACTING ASSOC PROFESSOR-HCOMP',
 'ACTING ASST PROFESSOR-HCOMP',
 'ASST PROFESSOR-ACAD YR-RECALL',
 'ACTING PROFESSOR - FISCAL YR',
 'HS ASSOC CLIN PROF-FY-GENCOMP',
 'ASSOC ADJUNCT PROFESSOR-SFT-VM',
 'ASST ADJUNCT PROFESSOR-SFT-VM',
 'ASSOCIATE PROFESSOR-MEDCOMP-A',
 'ACTING PROFESSOR-HCOMP',
 'PROFESSOR-ACAD YR-1/9TH PMT',
 'ADJ PROF-FY-BUS/ECON/ENG',
 'ASSOCIATE PROFESSOR-FY-GENCOMP',
 'ASSOC PROF IN RSDNC-AY-1/9TH',
 'HS ASST CLIN PROF-MEDCOMP-B',
 'ASSOC PROF IN RESIDENCE- AY',
 'ACT PROF-ACAD YR-BUS/ECON/ENG',
 'VSTG PROF-ACAD YR-BUS/ECON/ENG',
 'ASSOCIATE PROFESSOR-GENCOMP-A',
 'ATHLETICS PROFESSIONAL 4',
 'ACTING PROFESSOR-ACADEMIC YR',
 'CLIN PROF-DENTISTRY-50%/+ FY',
 'ASSOC ADJUNCT PROF-MEDCOMP-A',
 'ADJUNCT PROFESSOR-SFT-VM',
 'HS ASSOC CLIN PROF-MEDCOMP-B',
 'ACT ASSOC PROF-AY-BUS/ECON/ENG',
 'TECHNICAL PROJECT MGT PROF"L 5',
 'ASSOC PROF IN RES-FY-MEDCOMP',
 'PROFESSOR-LAW SCH SCALE-1/9TH',
 'HS ASSOC CLIN PROF-GENCOMP-B',
 'ATH PROFL 1',
 'ATH PROFL 3',
 'HS ASST CLIN PROF-FY',
 'ASST ADJ PROF-FY-B/E/E',
 'ASST PROF OF CLIN-FY',
 'ASSOC PROF-AY',
 'HS ASST CLIN PROF-HCOMP',
 'ASST PROF OF CLIN-HCOMP',
 'ASST PROF-AY',
 'ASSOC PROF OF CLIN-HCOMP',
 'VIS ASST PROF',
 'VIS ASST PROF-HCOMP',
 'ASST CLIN PROF-VOL',
 'ASST ADJ PROF-HCOMP',
 'ASST PROF IN RES-HCOMP',
 'ASSOC CLIN PROF-VOL',
 'ASST PROF-HCOMP',
 'PROF EMERITUS(WOS)',
 'PROF IN RES-HCOMP',
 'PROF-AY-B/E/E',
 'PROF-HCOMP',
 'PROF-AY',
 'ASST PROF-AY-B/E/E',
 'HS CLIN PROF-FY',
 'HS ASSOC CLIN PROF-HCOMP',
 'PROF-AY-LAW',
 'PROF OF CLIN-HCOMP',
 'ASSOC PROF-HCOMP',
 'HS CLIN PROF-HCOMP',
 'ASSOC PROF IN RES-HCOMP',
 'ASSOC ADJ PROF-HCOMP',
 'ASST ADJ PROF-AY',
 'PROF-FY',
 'HS ASSOC CLIN PROF-FY',
 'ASSOC PROF OF CLIN-FY',
 'PROF IN RES-FY',
 'PROF OF CLIN-FY',
 'ASSOC PROF-AY-B/E/E',
 'ASST PROF-AY-1/9-B/E/E',
 'ADJ PROF-HCOMP',
 'ADJ PROF-AY',
 'ADJ PROF-FY',
 'ASSOC ADJ PROF-AY',
 'ACT ASST PROF-FY',
 'PROF-FY-B/E/E',
 'VIS PROF',
 'ASSOC ADJ PROF-FY',
 'ASST PROF-SFT-VM',
 'ASSOC PROF-FY',
 'ACT PROF-AY-LAW',
 'ASST ADJ PROF-FY',
 'ASSOC PROF-SFT-VM',
 'VIS ASSOC PROF',
 'PROF IN RES-AY',
 'ATH PROFL 2',
 'PROF-SFT-VM',
 'TCHL PROJECT MGT PROFL 3',
 'ASST ADJ PROF-AY-B/E/E',
 'LIBRARY PROFL 4',
 'CLIN PROF-VOL',
 'UNIV PROF',
 'HS ASST CLIN PROF-AY',
 'ASST PROF-AY-1/9',
 'HS ASSOC CLIN PROF-AY',
 'VIS ASSOC PROF-HCOMP',
 'ASST PROF-FY',
 'ADJ PROF-AY-B/E/E',
 'TCHL PROJECT MGT PROFL 5',
 'TCHL PROJECT MGT PROFL 4',
 'ASSOC PROF-FY-B/E/E',
 'VIS PROF-HCOMP',
 'TCHL PROJECT MGT PROFL 2',
 'ADJ PROF-AY-1/9',
 'ACT ASSOC PROF-HCOMP',
 'HS CLIN PROF-AY',
 'MGT AND PROFL PRG UNTTL',
 'ASSOC PROF IN RES-FY',
 'ADJ PROF-FY-B/E/E',
 'ASSOC PROF IN RES-AY',
 'ACT ASST PROF-AY',
 'ACT ASSOC PROF-AY-B/E/E',
 'ASSOC ADJ PROF-AY-B/E/E',
 'PROF IN RES-AY-B/E/E',
 'PROF-AY-1/9',
 'ASST ADJ PROF-AY-1/9',
 'ASST PROF IN RES-AY',
 'ASSOC PROF IN RES-SFT-VM',
 'ASST PROF-FY-B/E/E',
 'ACT ASST PROF-HCOMP',
 'RES PROF-MILLER INST-AY',
 'ASSOC ADJ PROF-AY-1/9',
 'ASSOC PROF IN RES-AY-B/E/E',
 'REGENTS" PROF',
 'ACT PROF-HCOMP',
 'ASST PROF IN RES-FY',
 'ASSOC ADJ PROF-FY-B/E/E',
 'ADJ PROF-AY-1/9-B/E/E',
 'ASSOC PROF-AY-1/9',
 'ASST ADJ PROF-SFT-VM',
 'ASST PROF IN RES-AY-B/E/E',
 'ACT ASSOC PROF-AY',
 'ASSOC ADJ PROF-AY-1/9-B/E/E',
 'ASST ADJ PROF-AY-1/9-B/E/E',
 'PROF-AY-1/9-B/E/E',
 'ATH PROFL 4',
 'ACT PROF-AY',
 'CLIN PROF-DENT-50%/+-FY',
 'PRODUCT DEV PROFL 2',
 'ADJ PROF-SFT-VM',
 'ACT ASSOC PROF-FY',
 'VSTG PROF-ACAD YR-BUS/ENG',
 'PRODUCT DEV PROFL 3',
 'FEDERAL GOVERNMENT REL PROFL 4',
 'PROF-AY-1/9-BUS/ENG-RECALLED',
 'PRODUCT DEV PROFL 3 OP',
 'STATE GOVERNMENT REL PROFL 3',
 'STATE GOVERNMENT REL PROFL 2',
 'FEDERAL GOVERNMENT REL PROFL 5',
 'TCHL PROJECT MGT PROFL 3 OP',
 'ASST PROF IN RES-SFT-VM',
 'STATE GOVERNMENT REL PROFL 4',
 'PROF-ACAD YR-BUS/ENG-RECALLED',
 'REGL POLICY AND INTEL PROFL 4',
 'ACT ASST PROF-AY-B/E/E',
 'FEDERAL GOVERNMENT REL PROFL 3',
 'PROFESSOR-FY-GENCOMP',
 'PROF IN RES-SFT-VM',
 'STATE GOVERNMENT REL PROFL 5',
 'PRODUCT DEV PROFL 4',
 'REGL POLICY AND INTEL PROFL 3',
 'AUDIT PROFL 3',
 'REGENTS\\ PROF',
 'REGL POLICY AND INTEL PROFL 5',
 'STRAT SOURCING PROFL 4',
 'AUDIT PROFL 4',
 'AUDIT PROFL 2',
 'ADMIN NURSE PROFL 4',
 'AUDIT PROFL 5',
 'PROF IN RES-AY-1/9',
 'STRAT SOURCING PROFL 5',
 'CLIN APPLICATIONS PROFL 3',
 'CLIN APPLICATIONS PROFL 3 GF',
 'TCHL PROJECT MGT PROFL 3 GF',
 'TCHL PROJECT MGT PROFL 1',
 'CLIN APPLICATIONS PROFL 4',
 'CLIN APPLICATIONS PROFL 2',
 'LIBRARY PROFL 3',
 'CLIN APPLICATIONS PROFL 5',
 'PRODUCT DEV PROFL 3 GF',
 'ACT ASSOC PROF-AY-1/9-B/E/E',
 'STRAT SOURCING PROFL 3',
 'ASSOC PROF-AY-1/9-B/E/E',
 'TCHL PROJECT MGT PROFL 2 GF',
 'HEALTH PROFNS EDUC SPEC 2',
 'HEALTH PROFNS EDUC SPEC 4',
 'HEALTH PROFNS EDUC SPEC 3',
 'ETHICS AND CMPLNC PROFL 4',
 'ETHICS AND CMPLNC PROFL 3',
 'ASSOC ADJ PROF-SFT-VM',
 'HEALTH PROFNS EDUC MGR 2',
 'HEALTH PROFNS EDUC SUPV 2',
 'ETHICS AND CMPLNC PROFL 2',
 'MED LIBRARY PROFL 3',
 'AUDIT PROFL 1',
 'FEDERAL GOVT REL PROFL 3',
 'FEDERAL GOVT REL PROFL 4',
 'STATE GOVT REL PROFL 3',
 'STATE GOVT REL PROFL 2',
 'HEALTH PROFNS EDUC SPEC 4 GF',
 'ETHICS AND CMPLNC PROFL 5',
 'PRIVACY AND CMPLNC PROFL 3',
 'STATE GOVT REL PROFL 5',
 'STATE GOVT REL PROFL 4',
 'FEDERAL GOVT REL PROFL 5',
 'HEALTH PROFNS EDUC MGR 1',
 'MED LIBRARY PROFL 5',
 'PAT SFTY PROFL 4',
 'HEALTH PROFNS EDUC MGR 3',
 'PAT SFTY PROFL 2',
 'HEALTH PROFNS EDUC SPEC 3 GF',
 'HEALTH PROFNS EDUC SPEC 5',
 'HEALTH PROFNS EDUC SUPV 1',
 'ATH PROFL 1 BYA',
 'ATH PROFL 3 BYA',
 'ADJ PROF-AY-1/10-BEE',
 'VOLUNTEER SVC PROFL 4',
 'PAT REL PROFL 2',
 'PAT REL PROFL 3',
 'PAT REL PROFL 4',
 'BEH HEALTH PSYCHIATRIC PROFL 3',
 'BEH HEALTH PSYCHIATRIC PROFL 2',
 'ATH PROFL 4 BYA',
 'PROFL ENGR 4',
 'CLIN PROFL SVC MGR 4',
 'MED LIBRARY HC PROFL 3',
 'ATH PROFL 2 BYA',
 'BEH HEALTH PSYCHIATRIC PROFL 1',
 'BEH HEALTH PSYCHIATRIC PROFL 4',
 'BUS DEV HC PROFL 5',
 'BUS DEV HC PROFL 3 GF',
 'CLIN PROFL SVC MGR 3',
 'PRIVACY AND CMPLNC HC PROFL 4',
 'BUS DEV HC PROFL 4',
 'PROFL ENGR 3 GF',
 'PROVIDER ENROLLMENT PROFL 3',
 'ADMIN NURSE SHS PROFL 4',
 'BUS DEV HC PROFL 3',
 'RISK MGT HC PROFL 3',
 'RISK MGT HC PROFL 4',
 'CLIN PROFL SVC MGR 2',
 'PRIVACY AND CMPLNC HC PROFL 3',
 'MED LIBRARY HC PROFL 5',
 'DIALYSIS PROFL 4',
 'STRAT SOURCING PROFL 2',
 'PRIVACY AND CMPLNC HC PROFL 5',
 'MED LIBRARY HC PROFL 4',
 'PRIVACY AND CMPLNC HC PROFL 2',
 'PAT SFTY PROFL 5',
 'MED LIBRARY HC PROFL 3 GF',
 'ADJUNCT PROF-GENCOMP-A',
 'PROFL ENGR MGR 1',
 'PROVIDER ENROLLMENT PROFL 4',
 'ACT PROF-FY',
 'PROFL ENGR 5',
 'ADJ. PROF',
 'PROF OF CLIN-SFT-VM',
 'ETHICS AND CMPLNC PROFL 1',
 'CLIN APPLICATIONS PROFL 1',
 'ASSOC. PROF OF LAW',
 'PROF OF LAW',
 'ASSOC DIR (PROF)',
 'ASST PROF OF CLIN-SFT-VM',
 'VTG ASST PROF OF LAW',
 'PROFL ENGR 3',
 'VTG PROF OF LAW',
 'ASSOC PROF OF CLIN-SFT-VM',
 'CMTY HEALTH OUTR PROFL 2',
 'HS CLIN PROF-SFT-VM',
 'ANATOMICAL SVC PROFL 4',
 'CLIN PROF OF LAW',
 'PAT SFTY PROFL 3',
 'PROFESSOR (NON-TENURE)',
 'HS ASST CLIN PROF-SFT-VM',
 "REGENTS' PROF",
 'HS ASSOC CLIN PROF-SFT-VM',
 'ACT PROF-AY-B/E/E',
 'ASSOC ADJ PROF-AY-1/10',
 'SULLIVAN PROF OF LAW',
 'CMTY HEALTH OUTR PROFL 4',
 'CMTY HEALTH OUTR PROFL 3',
 'ACT ASST PROF-AY-1/9-B/E/E',
 'RECALLED PROF OF LAW',
 'ACT ASSOC PROF-SFT-VM',
 'RISK MGT HC PROFL 2',
 'ADJUNCT PROFESSOR',
 'ASSOCIATE PROFESSOR OF LAW',
 'CLINICAL PROFESSOR OF LAW',
 'PROFESSOR OF LAW',
 'ASSOCIATE DIRECTOR (PROF)',
 'VISITING PROFESSOR OF LAW',
 'SULLIVAN PROFESSOR OF LAW',
 'ASST PROF IN RES-AY-1/9',
 'PROFESSOR OF LAW (NON-TENURE)',
 'RECALLED PROFESSOR OF LAW',
 'RISK MGT HC PROFL 5',
 'CLIN PROFL SVC MGR 1']

In [26]:
[i for i in titles if "PROFESSIONAL" not in i and "PROFL" not in i]

['ASSISTANT PROFESSOR-ACAD YR',
 'ACT PROFESSOR-LAW SCHOOL SCALE',
 'ASSISTANT PROFESSOR-SFT-VM',
 'HS ASSISTANT CLIN PROF-HCOMP',
 'ASST PROF OF CLIN_____-HCOMP',
 'ASST PROF OF CLINICAL_____-FY',
 'HS ASST CLIN PROFESSOR-FY',
 'VST ASST PROFESSOR -FISCAL YR',
 'ASST CLINICAL PROFESSOR-VOL',
 'VISITING ASSISTANT PROF-HCOMP',
 'ASST PROF IN RESIDENCE - FY',
 'ASSISTANT PROF IN RES-HCOMP',
 'ASSISTANT ADJUNCT PROF-HCOMP',
 'ASST ADJUNCT PROF-MEDCOMP-A',
 'PROFESSOR - ACADEMIC YEAR',
 'ASSOCIATE PROF IN RES-HCOMP',
 'PROFESSOR-HCOMP',
 'ASST PROF-ACAD YR-BUS/ECON/ENG',
 'HS CLIN PROFESSOR-FISCAL YR',
 'PROFESSOR-ACAD YR-BUS/ECON/ENG',
 'ASSOC PROF OF CLIN_____-HCOMP',
 'PROFESSOR-ACAD YR-RECALLED',
 'HS ASSOCIATE CLIN PROF-HCOMP',
 'PROFESSOR-LAW SCHOOL SCALE',
 'PROFESSOR RECALLED-ACAD YR-1/9',
 'VIS ASST PROFESSOR-GENCOMP',
 'ASSOCIATE PROFESSOR-ACAD YR',
 'PROFESSOR OF CLINICAL___-HCOMP',
 'ASSOCIATE PROFESSOR-HCOMP',
 'ASSOCIATE ADJUNCT PROF-HCOMP',
 'ASSOC PROF-AY-BUS/ECON/ENG',
 'VST ASST PROFESSOR-ACAD YR-1/9',
 'PROFESSOR - FISCAL YR',
 'HS ASSOC CLIN PROFESSOR-FY',
 'HS CLINICAL PROFESSOR-HCOMP',
 'ASSOC PROF OF CLINICAL_____-FY',
 'PROFESSOR IN RESIDENCE-HCOMP',
 'PROFESSOR OF CLINICAL_____-FY',
 'HS ASST CLIN PROF-MEDCOMP-A',
 'PROFESSOR-GENCOMP-B',
 'PROFESSOR-FISCAL YR-RECALLED',
 'ASSISTANT PROFESSOR-HCOMP',
 'RESEARCH PROFESSOR',
 'VST ASST PROFESSOR-ACADEMIC YR',
 'ADJUNCT PROFESSOR-ACADEMIC YR',
 'ADJUNCT PROFESSOR - FISCAL YR',
 'PROFESSOR IN RESIDENCE - FY',
 'VISITING PROFESSOR-ACADEMIC YR',
 'VIS ASST PROFESSOR-MEDCOMP',
 'VSTG PROF-AY-1/9-BUS/ECON/ENGR',
 'ASSOC ADJUNCT PROFESSOR - AY',
 'PROFESSOR - FY -BUS/ECON/ENG',
 'ASSOC ADJUNCT PROFESSOR - FY',
 'ASSOC ADJUNCT PROF-GENCOMP-B',
 'HS ASSOC CLIN PROF-MEDCOMP-A',
 'ASST PROFESSOR - FISCAL YEAR',
 'HS CLIN PROF RECALLED-FY',
 'ASST ADJUNCT PROFESSOR - FY',
 'ADJUNCT PROFESSOR-HCOMP',
 'VISITING PROFESSOR-HCOMP',
 'ASSOCIATE PROFESSOR--SFT-VM',
 'ASST PROF IN RES-MEDCOMP-A',
 'ASST ADJUNCT PROFESSOR-ACAD YR',
 'PROFESSOR IN RESIDENCE-ACAD YR',
 'ASST ADJUNCT PROF-ACAD YR-1/9',
 'PROFESSOR EMERITUS (W/O SAL)',
 'TECHNICAL PROJECT MGT PROF"L 3',
 'ASST ADJ PROF-AY-BUS/ECON/ENG',
 'UNIVERSITY PROFESSOR',
 'PROFESSOR-MEDCOMP-A',
 'VST ASSOC PROFESSOR-AY-1/9TH',
 'VISITING ASSOCIATE PROF-HCOMP',
 'HS ASST CLIN PROFESSOR-ACAD YR',
 'ASSOC PROFESSOR - FISCAL YR',
 'HS ASSOC CLIN PROF-ACAD YR',
 'PROFESSOR-SFT-VM',
 'VST ASSOC PROFESSOR-ACAD YR',
 'VIS ASSOC PROFESSOR-GENCOMP',
 'REGENTS" PROFESSOR',
 'HS ASST CLIN PROF-FY-GENCOMP',
 'VISITING PROFESSOR - FISCAL YR',
 'VST PROFESSOR-ACAD YR-1/9 PMT',
 'ADJ PROF-ACAD YR-BUS/ECON/ENG',
 'PROF IN RES-MEDCOMP-A',
 'ASSOC PROFESSOR-AY-RECALLED',
 'VST ASSOC PROFESSOR-FISCAL YR',
 'CLINICAL PROFESSOR-VOLUNTEER',
 'ASST ADJ PROF-FY-BUS/ECON/ENG',
 'ASOC ADJUNCT PROF-GENCOMP-B',
 'ASSOC PROF-FY-BUS/ECON/ENG',
 'MGT AND PROF PROG (UNTITLED)',
 'AST PROF OF CLIN____-MEDCOMP-A',
 'ASST ADJUNCT PROF-GENCOMP-B',
 'TECHNICAL PROJECT MGT PROF"L 2',
 'ASST PROF IN RESIDENCE-ACAD YR',
 'ASSOC CLINICAL PROFESSOR-VOL',
 'HS CLINICAL PROFESSOR-ACAD YR',
 'ADJUNCT PROFESSOR-ACAD YR-1/9',
 'VST PROFESSOR-LAW SCHOOL SCALE',
 'TECHNICAL PROJECT MGT PROF"L 4',
 'PROFESSOR OF CLINICAL___',
 'ASSOC PROF IN RES-MEDCOMP-A',
 'ADJUNCT PROF-MEDCOMP-B',
 'PROF-AY-1/9-BUS/ECON/ENG-RECAL',
 'ASST PROF IN RES-GENCOMP-B',
 'ASSOC PROF IN RES-GENCOMP-B',
 'ASST ADJUNCT PROF-FY-GENCOMP',
 'PROF IN RES-GENCOMP-B',
 'ASO PROF OF CLIN___-MEDCOMP-A',
 'ASSOC PROF-RECALLED-AY-1/9TH',
 'PROF OF CLIN___-MEDCOMP-A',
 'HS CLIN PROF-MEDCOMP-A',
 'AST PROF OF CLIN___-MEDCOMP-A',
 'PROF IN RES-AY-BUS/ECON/ENG',
 'ASSOC ADJUNCT PROF-ACAD YR-1/9',
 'ACT ASST PROFESSOR-ACADEMIC YR',
 'CHIEF ADM & PROF SERVS OFFICER',
 'PROF-AY-BUS/ECON/ENG-RECALLED',
 'ADJ PROF-AY-1/9-BUS/ECON/ENG',
 'ASSOC PROF IN RESIDENCE-SFT-VM',
 'ASSISTANT PROFESSOR-FY-GENCOMP',
 'ASST PROF-FY-BUS/ECON/ENG',
 'ACT AST PROF-AY-BUS/ECON/ENG',
 'VIS ASSOC PROFESSOR-MEDCOMP',
 'AST PROF OF CLIN____-GENCOMP-A',
 'ASSISTANT PROFESSOR-AY-1/9TH',
 'ASSOC PROF IN RESIDENCE- FY',
 'ACT ASSOC PROFESSOR-ACAD YR',
 'ADJUNCT PROF-GENCOMP-B',
 'RES PROF-MILLER INST -ACAD YR',
 'ADJUNCT PROF-MEDCOMP-A',
 'ASST ADJUNCT PROF-MEDCOMP-B',
 'ASSOC PROFESSOR-FY-RECALL',
 'ASSO ADJ PROF-AY-BUS/ECON/ENG',
 'ASSOC ADJUNCT PROF-FY-GENCOMP',
 'PROFESSOR-AY-1/9-BUS/ECON/ENG',
 'ASSISTANT PROFESSOR-MEDCOMP-A',
 'ASST PROF-AY-1/9-BUS/ECON/ENG',
 'ASSOCIATE PROFESSOR-GENCOMP-B',
 'ACTING ASSOC PROFESSOR-HCOMP',
 'ACTING ASST PROFESSOR-HCOMP',
 'ASST PROFESSOR-ACAD YR-RECALL',
 'ACTING PROFESSOR - FISCAL YR',
 'HS ASSOC CLIN PROF-FY-GENCOMP',
 'ASSOC ADJUNCT PROFESSOR-SFT-VM',
 'ASST ADJUNCT PROFESSOR-SFT-VM',
 'ASSOCIATE PROFESSOR-MEDCOMP-A',
 'ACTING PROFESSOR-HCOMP',
 'PROFESSOR-ACAD YR-1/9TH PMT',
 'ADJ PROF-FY-BUS/ECON/ENG',
 'ASSOCIATE PROFESSOR-FY-GENCOMP',
 'ASSOC PROF IN RSDNC-AY-1/9TH',
 'HS ASST CLIN PROF-MEDCOMP-B',
 'ASSOC PROF IN RESIDENCE- AY',
 'ACT PROF-ACAD YR-BUS/ECON/ENG',
 'VSTG PROF-ACAD YR-BUS/ECON/ENG',
 'ASSOCIATE PROFESSOR-GENCOMP-A',
 'ACTING PROFESSOR-ACADEMIC YR',
 'CLIN PROF-DENTISTRY-50%/+ FY',
 'ASSOC ADJUNCT PROF-MEDCOMP-A',
 'ADJUNCT PROFESSOR-SFT-VM',
 'HS ASSOC CLIN PROF-MEDCOMP-B',
 'ACT ASSOC PROF-AY-BUS/ECON/ENG',
 'TECHNICAL PROJECT MGT PROF"L 5',
 'ASSOC PROF IN RES-FY-MEDCOMP',
 'PROFESSOR-LAW SCH SCALE-1/9TH',
 'HS ASSOC CLIN PROF-GENCOMP-B',
 'HS ASST CLIN PROF-FY',
 'ASST ADJ PROF-FY-B/E/E',
 'ASST PROF OF CLIN-FY',
 'ASSOC PROF-AY',
 'HS ASST CLIN PROF-HCOMP',
 'ASST PROF OF CLIN-HCOMP',
 'ASST PROF-AY',
 'ASSOC PROF OF CLIN-HCOMP',
 'VIS ASST PROF',
 'VIS ASST PROF-HCOMP',
 'ASST CLIN PROF-VOL',
 'ASST ADJ PROF-HCOMP',
 'ASST PROF IN RES-HCOMP',
 'ASSOC CLIN PROF-VOL',
 'ASST PROF-HCOMP',
 'PROF EMERITUS(WOS)',
 'PROF IN RES-HCOMP',
 'PROF-AY-B/E/E',
 'PROF-HCOMP',
 'PROF-AY',
 'ASST PROF-AY-B/E/E',
 'HS CLIN PROF-FY',
 'HS ASSOC CLIN PROF-HCOMP',
 'PROF-AY-LAW',
 'PROF OF CLIN-HCOMP',
 'ASSOC PROF-HCOMP',
 'HS CLIN PROF-HCOMP',
 'ASSOC PROF IN RES-HCOMP',
 'ASSOC ADJ PROF-HCOMP',
 'ASST ADJ PROF-AY',
 'PROF-FY',
 'HS ASSOC CLIN PROF-FY',
 'ASSOC PROF OF CLIN-FY',
 'PROF IN RES-FY',
 'PROF OF CLIN-FY',
 'ASSOC PROF-AY-B/E/E',
 'ASST PROF-AY-1/9-B/E/E',
 'ADJ PROF-HCOMP',
 'ADJ PROF-AY',
 'ADJ PROF-FY',
 'ASSOC ADJ PROF-AY',
 'ACT ASST PROF-FY',
 'PROF-FY-B/E/E',
 'VIS PROF',
 'ASSOC ADJ PROF-FY',
 'ASST PROF-SFT-VM',
 'ASSOC PROF-FY',
 'ACT PROF-AY-LAW',
 'ASST ADJ PROF-FY',
 'ASSOC PROF-SFT-VM',
 'VIS ASSOC PROF',
 'PROF IN RES-AY',
 'PROF-SFT-VM',
 'ASST ADJ PROF-AY-B/E/E',
 'CLIN PROF-VOL',
 'UNIV PROF',
 'HS ASST CLIN PROF-AY',
 'ASST PROF-AY-1/9',
 'HS ASSOC CLIN PROF-AY',
 'VIS ASSOC PROF-HCOMP',
 'ASST PROF-FY',
 'ADJ PROF-AY-B/E/E',
 'ASSOC PROF-FY-B/E/E',
 'VIS PROF-HCOMP',
 'ADJ PROF-AY-1/9',
 'ACT ASSOC PROF-HCOMP',
 'HS CLIN PROF-AY',
 'ASSOC PROF IN RES-FY',
 'ADJ PROF-FY-B/E/E',
 'ASSOC PROF IN RES-AY',
 'ACT ASST PROF-AY',
 'ACT ASSOC PROF-AY-B/E/E',
 'ASSOC ADJ PROF-AY-B/E/E',
 'PROF IN RES-AY-B/E/E',
 'PROF-AY-1/9',
 'ASST ADJ PROF-AY-1/9',
 'ASST PROF IN RES-AY',
 'ASSOC PROF IN RES-SFT-VM',
 'ASST PROF-FY-B/E/E',
 'ACT ASST PROF-HCOMP',
 'RES PROF-MILLER INST-AY',
 'ASSOC ADJ PROF-AY-1/9',
 'ASSOC PROF IN RES-AY-B/E/E',
 'REGENTS" PROF',
 'ACT PROF-HCOMP',
 'ASST PROF IN RES-FY',
 'ASSOC ADJ PROF-FY-B/E/E',
 'ADJ PROF-AY-1/9-B/E/E',
 'ASSOC PROF-AY-1/9',
 'ASST ADJ PROF-SFT-VM',
 'ASST PROF IN RES-AY-B/E/E',
 'ACT ASSOC PROF-AY',
 'ASSOC ADJ PROF-AY-1/9-B/E/E',
 'ASST ADJ PROF-AY-1/9-B/E/E',
 'PROF-AY-1/9-B/E/E',
 'ACT PROF-AY',
 'CLIN PROF-DENT-50%/+-FY',
 'ADJ PROF-SFT-VM',
 'ACT ASSOC PROF-FY',
 'VSTG PROF-ACAD YR-BUS/ENG',
 'PROF-AY-1/9-BUS/ENG-RECALLED',
 'ASST PROF IN RES-SFT-VM',
 'PROF-ACAD YR-BUS/ENG-RECALLED',
 'ACT ASST PROF-AY-B/E/E',
 'PROFESSOR-FY-GENCOMP',
 'PROF IN RES-SFT-VM',
 'REGENTS\\ PROF',
 'PROF IN RES-AY-1/9',
 'ACT ASSOC PROF-AY-1/9-B/E/E',
 'ASSOC PROF-AY-1/9-B/E/E',
 'HEALTH PROFNS EDUC SPEC 2',
 'HEALTH PROFNS EDUC SPEC 4',
 'HEALTH PROFNS EDUC SPEC 3',
 'ASSOC ADJ PROF-SFT-VM',
 'HEALTH PROFNS EDUC MGR 2',
 'HEALTH PROFNS EDUC SUPV 2',
 'HEALTH PROFNS EDUC SPEC 4 GF',
 'HEALTH PROFNS EDUC MGR 1',
 'HEALTH PROFNS EDUC MGR 3',
 'HEALTH PROFNS EDUC SPEC 3 GF',
 'HEALTH PROFNS EDUC SPEC 5',
 'HEALTH PROFNS EDUC SUPV 1',
 'ADJ PROF-AY-1/10-BEE',
 'ADJUNCT PROF-GENCOMP-A',
 'ACT PROF-FY',
 'ADJ. PROF',
 'PROF OF CLIN-SFT-VM',
 'ASSOC. PROF OF LAW',
 'PROF OF LAW',
 'ASSOC DIR (PROF)',
 'ASST PROF OF CLIN-SFT-VM',
 'VTG ASST PROF OF LAW',
 'VTG PROF OF LAW',
 'ASSOC PROF OF CLIN-SFT-VM',
 'HS CLIN PROF-SFT-VM',
 'CLIN PROF OF LAW',
 'PROFESSOR (NON-TENURE)',
 'HS ASST CLIN PROF-SFT-VM',
 "REGENTS' PROF",
 'HS ASSOC CLIN PROF-SFT-VM',
 'ACT PROF-AY-B/E/E',
 'ASSOC ADJ PROF-AY-1/10',
 'SULLIVAN PROF OF LAW',
 'ACT ASST PROF-AY-1/9-B/E/E',
 'RECALLED PROF OF LAW',
 'ACT ASSOC PROF-SFT-VM',
 'ADJUNCT PROFESSOR',
 'ASSOCIATE PROFESSOR OF LAW',
 'CLINICAL PROFESSOR OF LAW',
 'PROFESSOR OF LAW',
 'ASSOCIATE DIRECTOR (PROF)',
 'VISITING PROFESSOR OF LAW',
 'SULLIVAN PROFESSOR OF LAW',
 'ASST PROF IN RES-AY-1/9',
 'PROFESSOR OF LAW (NON-TENURE)',
 'RECALLED PROFESSOR OF LAW']

In [58]:
def title_assign(x):
    if "PROFL" in x or "PROFESSIONAL" in x:
        return "OTHER"
    elif "VST" in x and "ASST" in x:
        return "VST ASST"
    elif "VST" in x and "ASSOC" in x:
        return "VST ASSOC"
    elif "VST" in x:
        return "VST PROF"
    elif "ADJ" in x and "ASST" in x:
        return "ADJ ASST"
    elif ("ASOC" in x or "ASSOC" in x) and "ADJ" in x:
        return "ADJ ASOC"
    elif "ADJ" in x:
        return "ADJ PROF"
    elif ("ASST" in x or "ASSIST" in x) and "PROF" in x:
        return "ASST PROF"
    elif "ASSOC" in x and "PROF" in x:
        return "ASSOC PROF"
    elif "PROF" in x:
        return "PROF"
    else:
        return "OTHER"

In [59]:
prof_rows["title"] = prof_rows["title"].apply(title_assign)

/var/folders/py/yn4jz9f166sd76n0j33k5ny00000gn/T/ipykernel_30120/1405741927.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prof_rows["title"] = prof_rows["title"].apply(title_assign)

In [60]:
prof_rows[prof_rows["title"]!="OTHER"]

,row_names,id,year,location,first.name,last.name,title,gross.pay,regular.pay,overtime.pay,other.pay
0,1,1,2010,Santa Cruz,*****,*****,ASST PROF,74511.10,69999.96,0.0,4511.14
978,979,979,2010,Berkeley,***********,***********,PROF,114204.26,84204.25,0.0,30000.01
14803,14804,14804,2010,Davis,***********,***********,ASST PROF,115215.50,88198.64,0.0,27016.86
15350,15351,15351,2010,Davis,***********,***********,ASST PROF,140080.06,68996.04,0.0,71084.02
18522,18523,18523,2010,Davis,***********,***********,ASST PROF,122105.97,76243.65,0.0,45862.32
...,...,...,...,...,...,...,...,...,...,...,...
3024446,3024447,210073,2020,Los Angeles,ALEXANDER,MAZZAFERRO,ASST PROF,39417.00,39417.00,0.0,0.00
3024450,3024451,210077,2020,San Diego,WILLIAM,MAZZEI,PROF,218546.00,163606.00,0.0,54940.00
3024455,3024456,210082,2020,Los Angeles,JOHN,MAZZIOTTA,PROF,1035172.00,695172.00,0.0,340000.00
3024456,3024457,210083,2020,Los Angeles,MAURIZIO,MAZZOCCO,ASSOC PROF,283000.00,283000.00,0.0,0.00
3024465,3024466,210092,2020,Berkeley,MASSIMO,MAZZOTTI,PROF,141858.00,141858.00,0.0,0.00

In [63]:
prof_rows.groupby("title")["gross.pay"].mean().sort_values()

title
VST ASSOC      18720.152473
VST ASST       20629.142353
VST PROF       28685.205937
ADJ ASST       83534.351612
ADJ ASOC       97817.998927
ADJ PROF       98626.052368
ASST PROF     150323.815197
ASSOC PROF    171999.885210
PROF          217624.153142
Name: gross.pay, dtype: float64

In [64]:
prof_rows.groupby("location")["gross.pay"].mean().sort_values()

location
UCOP                        20223.674186
DANR                        25276.898667
Hastings                    61655.841121
Hastings College Of Law     62853.018868
Merced                     113714.270824
Riverside                  118308.432540
Santa Cruz                 123314.845434
Santa Barbara              141446.017037
Berkeley                   150359.078108
Davis                      172797.047093
Irvine                     177607.196310
San Diego                  197651.592376
San Francisco              207881.533423
Los Angeles                209347.684015
Name: gross.pay, dtype: float64

In [67]:
pd.DataFrame(prof_rows.groupby(["location","title"])["gross.pay"].mean())

                           gross.pay
location   title
Berkeley   ADJ ASOC     82331.859099
           ADJ ASST     56037.976727
           ADJ PROF    101011.935352
           ASSOC PROF  123341.595873
           ASST PROF    98872.368977
...                              ...
Santa Cruz VST ASST     27536.569091
           VST PROF     16009.400000
UCOP       ASSOC PROF    9005.248571
           ASST PROF     8673.282000
           PROF         24619.833548

[101 rows x 1 columns]