## Connect to Database and pull data

In [1]:
!pip install pymysql
!pip install boto3
!pip install sqlalchemy
!pip install python-dotenv

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 1.9 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1
Requirement already satisfied: boto3 in /Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages (1.21.32)
Requirement already satisfied: botocore<1.25.0,>=1.24.32 in /Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages (from boto3) (1.24.32)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages (from boto3) (0.10.0)
Requirement already satisfied: s3transfer<0.6.0,>=0.5.0 in /Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages (from boto3) (0.5.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages (from botocore<1.25.0,>=1.24.32->boto3) (2.8.2)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages (from botocore<1.25.0,>=1.24.32->boto3) (1.26.9)
Requirement already satisfied: six>=1.5 in /Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.25.0,>=1.24.32->boto3) (1.16.0)
Requirement already satisfied: sqlalchemy in /Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages (1.4.32)
Requirement already satisfied: greenlet!=0.4.17 in /Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages (from sqlalchemy) (1.1.1)
Collecting python-dotenv
  Downloading python_dotenv-1.1.0-py3-none-any.whl (20 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-1.1.0

In [2]:
# package for env variables in google colab: https://pypi.org/project/colab-env/
!pip install colab-env -qU
import colab_env

ImportError: colab-env only works in a Google Colab notebook

In [4]:
from colab_env import envvar_handler # modify env variables in var.env file in google drive

ImportError: colab-env only works in a Google Colab notebook

In [19]:
import pymysql
import sys
import boto3
import os

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [8]:
connection = pymysql.connect(
    host=MAS405_AWS_MY_DB_ROUSER_HOST,
    user=MAS405_AWS_MY_DB_ROUSER_USER,
    port=MAS405_AWS_MY_DB_ROUSER_PORT,
    passwd=MAS405_AWS_MY_DB_ROUSER_PW,
    database=MAS405_AWS_MY_DB_ROUSER_DBNAME
)

In [47]:
with connection.cursor() as cursor:
    cursor.execute("SHOW TABLES")
    tables = cursor.fetchall()

# Print table names
for table in tables:
    print(table[0])

SuperBowl_coinTosses
UC_salaries_data
google_elev_68sites
iris_data

In [ ]:
# from sqlalchemy import select
# stmt = select(user_table).where(user_table.c.name == "spongebob")
# print(stmt)

In [86]:
# years: 2010-2014
# 3024476 rows
# features: row_names	id	year	location	first.name	last.name	title	gross.pay	regular.pay	overtime.pay	other.pay
# location: DIVISION OF AGRICULTURE AND NATURAL RESOURCES (DANR)
# UCOP: university california office of the president
avg_loc_pay_df = pd.read_sql("SELECT location, AVG(`gross.pay`) FROM UC_salaries_data GROUP BY location", con=connection)
avg_loc_pay_df

<ipython-input-86-f645626e0120>:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  avg_loc_pay_df = pd.read_sql("SELECT location, AVG(`gross.pay`) FROM UC_salaries_data GROUP BY location", con=connection)

                   location  AVG(`gross.pay`)
0                Santa Cruz      26480.185848
1                  Berkeley      33418.287407
2                      DANR      34808.033162
3                     Davis      48795.614970
4                    Irvine      44389.647911
5               Los Angeles      51069.148947
6                    Merced      28558.416354
7                 Riverside      29015.387886
8                 San Diego      48018.481947
9             San Francisco      82919.020569
10            Santa Barbara      27167.823724
11                     UCOP      87482.700910
12                   ASUCLA       7729.955310
13  Hastings College Of Law      32675.792004
14                 Hastings      26595.393851

In [9]:
pd.read_sql("SELECT * FROM UC_salaries_data LIMIT 10", connection)

/Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,row_names,id,year,location,first.name,last.name,title,gross.pay,regular.pay,overtime.pay,other.pay
0,1,1,2010,Santa Cruz,*****,*****,ASSISTANT PROFESSOR-ACAD YR,74511.10,69999.96,0.0,4511.14
1,2,2,2010,Berkeley,***********,***********,GRAD STDNT RES-FULL FEE REM,5369.42,5369.42,0.0,0.00
2,3,3,2010,Berkeley,***********,***********,TEACHING ASSISTANT - GSHIP,4802.00,4802.00,0.0,0.00
3,4,4,2010,Berkeley,***********,***********,GRAD STDNT RES- NO REMISSION,3409.01,3409.01,0.0,0.00
4,5,5,2010,Berkeley,***********,***********,GRAD STDNT RES-FULL FEE REM,11673.90,11673.90,0.0,0.00
5,6,6,2010,Berkeley,***********,***********,ASSISTANT II,1712.44,1698.76,0.0,13.68
6,7,7,2010,Berkeley,***********,***********,ASSISTANT I,1325.50,1325.50,0.0,0.00
7,8,8,2010,Berkeley,***********,***********,GRAD STDNT RES-FULL FEE REM,6861.94,6861.94,0.0,0.00
8,9,9,2010,Berkeley,***********,***********,ASSISTANT I,1232.00,1232.00,0.0,0.00
9,10,10,2010,Berkeley,***********,***********,READER - GSHIP,11067.81,11067.81,0.0,0.00

In [44]:
df = pd.read_sql("SELECT * FROM UC_salaries_data", connection)
df.head()

/Users/claytonchan/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,row_names,id,year,location,first.name,last.name,title,gross.pay,regular.pay,overtime.pay,other.pay
0,1,1,2010,Santa Cruz,*****,*****,ASSISTANT PROFESSOR-ACAD YR,74511.10,69999.96,0.0,4511.14
1,2,2,2010,Berkeley,***********,***********,GRAD STDNT RES-FULL FEE REM,5369.42,5369.42,0.0,0.00
2,3,3,2010,Berkeley,***********,***********,TEACHING ASSISTANT - GSHIP,4802.00,4802.00,0.0,0.00
3,4,4,2010,Berkeley,***********,***********,GRAD STDNT RES- NO REMISSION,3409.01,3409.01,0.0,0.00
4,5,5,2010,Berkeley,***********,***********,GRAD STDNT RES-FULL FEE REM,11673.90,11673.90,0.0,0.00

In [45]:
df = df.dropna()
df

,row_names,id,year,location,first.name,last.name,title,gross.pay,regular.pay,overtime.pay,other.pay
0,1,1,2010,Santa Cruz,*****,*****,ASSISTANT PROFESSOR-ACAD YR,74511.10,69999.96,0.0,4511.14
1,2,2,2010,Berkeley,***********,***********,GRAD STDNT RES-FULL FEE REM,5369.42,5369.42,0.0,0.00
2,3,3,2010,Berkeley,***********,***********,TEACHING ASSISTANT - GSHIP,4802.00,4802.00,0.0,0.00
3,4,4,2010,Berkeley,***********,***********,GRAD STDNT RES- NO REMISSION,3409.01,3409.01,0.0,0.00
4,5,5,2010,Berkeley,***********,***********,GRAD STDNT RES-FULL FEE REM,11673.90,11673.90,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...
3024470,3024471,210097,2020,Riverside,BARA,MBOUP,MUSICIAN 2,4747.00,4747.00,0.0,0.00
3024471,3024472,210098,2020,Irvine,EPHANTUS,MBUGUA,REG RESP THER 1,38428.00,31437.00,713.0,6278.00
3024472,3024473,210099,2020,Los Angeles,PAULINE,MBUGUA,BLANK AST 2 PD,41089.00,39061.00,1953.0,75.00
3024473,3024474,210100,2020,Irvine,BERNADETTE,MBURU,PSYCHIATRIC TCHN SR,55677.00,52624.00,40.0,3013.00
3024474,3024475,210101,2020,Davis,PETER,MBUTHIA,MED CTR CUSTODIAN SR,38172.00,31671.00,1625.0,4876.00

In [84]:
pat = r"""(?ix)                     # (?i)=ignore-case  (?x)=verbose mode
    \b(?:                               # word-start, then one of…
        prof(?:essors?\b|\.?\b)         #  "professor" / "professors" / "prof" / "prof."
      | lect(?:urer?s?\b|\b)            #  "lecturer(s)" / "lect"
    )
"""
prof_rows = df[df['title'].str.contains(pat,case = False,na = False)]

In [85]:
prof_rows

,row_names,id,year,location,first.name,last.name,title,gross.pay,regular.pay,overtime.pay,other.pay
0,1,1,2010,Santa Cruz,*****,*****,ASSISTANT PROFESSOR-ACAD YR,74511.10,69999.96,0.0,4511.14
20,21,21,2010,Berkeley,***********,***********,LECTURER - ACADEMIC YEAR,30364.71,25454.75,0.0,4909.96
94,95,95,2010,Berkeley,***********,***********,LECTURER - ACADEMIC YEAR,29248.46,29248.46,0.0,0.00
175,176,176,2010,Berkeley,***********,***********,LECTURER - ACADEMIC YEAR,27258.69,27058.69,0.0,200.00
178,179,179,2010,Berkeley,***********,***********,LECTURER - ACADEMIC YEAR,28679.78,28679.78,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...
3024446,3024447,210073,2020,Los Angeles,ALEXANDER,MAZZAFERRO,ASST PROF-AY,39417.00,39417.00,0.0,0.00
3024450,3024451,210077,2020,San Diego,WILLIAM,MAZZEI,HS CLIN PROF-HCOMP,218546.00,163606.00,0.0,54940.00
3024455,3024456,210082,2020,Los Angeles,JOHN,MAZZIOTTA,PROF-HCOMP,1035172.00,695172.00,0.0,340000.00
3024456,3024457,210083,2020,Los Angeles,MAURIZIO,MAZZOCCO,ASSOC PROF-AY-B/E/E,283000.00,283000.00,0.0,0.00
3024465,3024466,210092,2020,Berkeley,MASSIMO,MAZZOTTI,PROF-AY,141858.00,141858.00,0.0,0.00

In [81]:
titles = df["title"].unique().tolist()
titles = [i for i in titles if "LECT" in i]
titles

['LECTURER - ACADEMIC YEAR',
 'LECTURER IN SUMMER SESSION',
 'LECTURER - ACADEMIC YEAR - 1/9',
 'ELECTRONIC COMM SPECIALIST 3',
 'LECTURER-AY-1/9-CONTINUING',
 'LECTURER-AY-CONTINUING APPT.',
 'TECHNICIAN,ELECTRONICS,TRAINEE',
 'LECTURER - FISCAL YEAR',
 'OFFICER, ELECTED, STUDENT GOVT',
 'TECHNICIAN, ELECTRONICS, SR',
 'COLLECTIONS REPRESENTATIVE, SR',
 'SR LECT W/SEC EMPL-ACADEMIC YR',
 'LECTURER-MISC/PART-TIME',
 'LECTURER W/SEC EMPL-ACAD YR',
 'ELECTRICIAN',
 'INTELLECTUAL PROPERTY OFFICR 4',
 'LECTURER-FY-CONTINUING APPT.',
 'TECHNICIAN, ELECTRONICS',
 'TECHNICIAN, ELECTROCARDIOGRAPH',
 'TECHNICIAN, ELECTRONICS, PRIN',
 'COLLECTIONS REPRESENTATIVE',
 'TECHNICIAN, ELECTROCARDIOG, SR',
 'LECTURER-PSOE-ACAD YR-100%',
 'INTELLECTUAL PROPERTY OFFICR 1',
 'SR LECT W/SEC EMPL - FISCAL YR',
 'SR. LECTURER-AY-CONTINUING',
 'HIGH VOLT ELECTRICIAN',
 'ELECTRONIC COMM SPEC 4',
 'ELECTRICIAN, SUPERVISING',
 'ARTS AND LECTURES MANAGER',
 'ELECTRICIAN, MARINE, UTILITY',
 'ELECTRICIAN, APPRENTICE',
 'TECHNICIAN, ELECTRONICS, SUPVR',
 'REGISTRAR/COLLECTION MANAGER 1',
 'COLLECTIONS REP, SR-SUPVR',
 'REGENTS" LECTURER',
 'ELECTRICIAN, LEAD',
 'HIGH VOLT ELECTRICIAN, APPREN',
 'TECHNICIAN, ELECT., P.D.',
 'SR LECTURER - ACADEMIC YEAR',
 'ELECTRICIAN I',
 'LECT W/SEC-FISCAL YR-RECALL',
 'HIGH VOLT ELECTRICIAN, LEAD',
 'SR LECT W/SEC-ACAD YR -RECALL',
 'ELECTRICIAN II',
 'LECTURER-PSOE-ACAD YR-1/9-100%',
 'REGISTRAR/COLLECTION SUPR 2',
 'CHILD DEVELOPMENT DEMO LECT',
 'SR LECT W/SEC-AY-RECALL-1/9TH',
 'SR.LECT.-AY-1/9-CONTINUING',
 'ELECTRONIC COMMUNICATION MGR 1',
 'INTELLECTUAL PROPERTY MGR 2',
 'LECT-PSOE-ACAD YR-PART TIME',
 'SR LECT W/SEC EMPL EMERITUS',
 'ELECTRICIAN LEADWORKER',
 'COLLECTIONS MANAGER',
 'LECTURER/SR. LECTURER-WOS-FY',
 'ARTS & LECTURES MGR SUPERVISOR',
 'ELECTRONIC COMM SPEC 5',
 'INTELLECTUAL PROPERTY OFFICR 3',
 'INTELLECTUAL PROPERTY MGR 3',
 'SR LECT W/SEC-FISCAL YR-RECALL',
 'ELECTRONIC COMM SUPR 2',
 'LECT W/SEC-ACAD YR-RECALL',
 'SENIOR LECTURER SOE-HCOMP',
 'LECT W/SEC-AY-RECALL-1/9TH',
 'CHILD DEVEL.DEMO.LECT-CONTIN',
 'ELECTRICIAN SUPV, ASST',
 'SR LECTURER-PSOE-ACAD YR-100%',
 'ELECTRONIC COMM SPEC 2',
 'TECHNICIAN,ELECTROCARDI, PRIN',
 'LECT-AY-1/9',
 'LECT IN SUMMER SESSION',
 'LECT-AY',
 'LECT-AY-CONTINUING',
 'ELECTR TCHN TRAINEE',
 'ELECTR TCHN',
 'LECT PSOE-AY-100%',
 'LECT-FY',
 'LECT-AY-1/9-CONTINUING',
 'ELECTED OFCR STDT GOVERNMENT',
 'LECT-MISCELLANEOUS/PART TIME',
 'ELECTR TCHN PRN',
 'COLLECTIONS REPR SR',
 'SR LECT SOE-AY',
 'LECT SOE-AY',
 'ELECTRN',
 'LECT-FY-CONTINUING',
 'INTELLECTUAL PROPERTY OFCR 4',
 'ELECTR TCHN SR',
 'COLLECTIONS REPR',
 'ELECTR COMM SPEC 3',
 'ELECTROCARDIOGRAPH TCHN',
 'ELECTNR',
 'ELECTROCARDIOGRAPH TCHN SR',
 'ELECTR TCHN SR SUPV',
 'SR LECT SOE-FY',
 'MED CTR ELECTR TCHN PRN',
 'SR LECT-AY-CONTINUING',
 'HIGH VOLT ELECTRN',
 'ELECTRN SUPV',
 'ARTS AND LECTURES MGR',
 'ELECTR TCHN SUPV',
 'SR LECT-FY-CONTINUING',
 'MARINE UTILITY ELECTRN',
 'SR LECT SOE-EMERITUS (WOS)',
 'REGISTRAR COLLECTION MGR 1',
 'ELECTRN LD',
 'ELECTROCARDIOGRAPH TCHN PD',
 'HIGH VOLT ELECTRN APPR',
 'INTELLECTUAL PROPERTY OFCR 2',
 'SR LECT-AY',
 'ELECTR COMM SPEC 4',
 'ELECTRN 2',
 'MED CTR ELECTR TCHN SR',
 'ELECTRN 1',
 'HIGH VOLT ELECTRN LD',
 'MED CTR ELECTR TCHN PRN SUPV',
 'LECT SOE-EMERITUS(WOS)',
 'REGISTRAR COLLECTION SUPV 2',
 'ELECTRN APPR',
 'SR LECT SOE-HCOMP',
 'SR LECT-AY-1/9',
 'ELECTR COMM SUPV 2',
 'LECT/SR LECT(WOS)',
 'ELECTR COMM MGR 1',
 'SR LECT PSOE-AY-100%',
 'ARTS AND LECTURES SUPV',
 'ELECTRN WORKER LD',
 'COLLECTIONS MGR',
 'CHILD DEV DEMO LECT-CONTINUING',
 'REGENTS" LECT',
 'ALARM ELECTRN LD',
 'COLLECTIONS REPR SR SUPV',
 'LECT PSOE-AY-PART TIME',
 'ELECTROCARDIOGRAPH TCHN PRN',
 'ELECTRN AST SUPV',
 'MED CTR ELECTR TCHN',
 'INTELLECTUAL PROPERTY OFCR 3',
 'INTELLECTUAL PROPERTY MGR 1',
 'REGENTS\\ LECT',
 'INTELLECTUAL PROPERTY OFCR 5',
 'INTELLECTUAL PROPERTY OFCR 1',
 'CHILD DEV DEMO LECT',
 'SR LECT-AY-1/9-CONTINUING',
 'LECT PSOE-FY-100%',
 'ELECTRN LD MC',
 'LECT SOE-FY',
 'LECT PSOE-AY-1/9-100%',
 'MED CTR ELECTR TCHN TRAINEE',
 'MED CTR ELECTR TCHN SUPV SR',
 'ELECTED OFCR STDT GOVT',
 'LECT-AY-1/10',
 'LECTR/SR. LECR NON-REP AY',
 'LECT-AY-1/10-CONTINUING',
 'LECTR/SR. LECR NON-REP FY',
 'LECT SOE-AY-1/9',
 'INTELLECTUAL PROPERTY SUPV 2',
 'ELECTRN OPR 3',
 'LECT PSOE-AY',
 'LECTURER',
 "REGENTS' LECT",
 'SR LECT PSOE-AY',
 'LECT PSOE-AY-1/9',
 'SR LECT-FY',
 'LECT SOE-AY-B/E/E',
 'LECT PSOE-AY-B/E/E',
 'LECT SOE-FY-B/E/E',
 'SR LECT SOE-AY-B/E/E',
 'SR LECT SOE-AY-LAW',
 'ELECTRN SPEC',
 'LECT SOE-HCOMP',
 'ACT LECT PSOE-AY',
 'SR LECT SOE-AY-1/9']

In [83]:
"LECT" in "ELECTRICIAN"

True

In [26]:
[i for i in titles if "PROFESSIONAL" not in i and "PROFL" not in i]

['ASSISTANT PROFESSOR-ACAD YR',
 'ACT PROFESSOR-LAW SCHOOL SCALE',
 'ASSISTANT PROFESSOR-SFT-VM',
 'HS ASSISTANT CLIN PROF-HCOMP',
 'ASST PROF OF CLIN_____-HCOMP',
 'ASST PROF OF CLINICAL_____-FY',
 'HS ASST CLIN PROFESSOR-FY',
 'VST ASST PROFESSOR -FISCAL YR',
 'ASST CLINICAL PROFESSOR-VOL',
 'VISITING ASSISTANT PROF-HCOMP',
 'ASST PROF IN RESIDENCE - FY',
 'ASSISTANT PROF IN RES-HCOMP',
 'ASSISTANT ADJUNCT PROF-HCOMP',
 'ASST ADJUNCT PROF-MEDCOMP-A',
 'PROFESSOR - ACADEMIC YEAR',
 'ASSOCIATE PROF IN RES-HCOMP',
 'PROFESSOR-HCOMP',
 'ASST PROF-ACAD YR-BUS/ECON/ENG',
 'HS CLIN PROFESSOR-FISCAL YR',
 'PROFESSOR-ACAD YR-BUS/ECON/ENG',
 'ASSOC PROF OF CLIN_____-HCOMP',
 'PROFESSOR-ACAD YR-RECALLED',
 'HS ASSOCIATE CLIN PROF-HCOMP',
 'PROFESSOR-LAW SCHOOL SCALE',
 'PROFESSOR RECALLED-ACAD YR-1/9',
 'VIS ASST PROFESSOR-GENCOMP',
 'ASSOCIATE PROFESSOR-ACAD YR',
 'PROFESSOR OF CLINICAL___-HCOMP',
 'ASSOCIATE PROFESSOR-HCOMP',
 'ASSOCIATE ADJUNCT PROF-HCOMP',
 'ASSOC PROF-AY-BUS/ECON/ENG',
 'VST ASST PROFESSOR-ACAD YR-1/9',
 'PROFESSOR - FISCAL YR',
 'HS ASSOC CLIN PROFESSOR-FY',
 'HS CLINICAL PROFESSOR-HCOMP',
 'ASSOC PROF OF CLINICAL_____-FY',
 'PROFESSOR IN RESIDENCE-HCOMP',
 'PROFESSOR OF CLINICAL_____-FY',
 'HS ASST CLIN PROF-MEDCOMP-A',
 'PROFESSOR-GENCOMP-B',
 'PROFESSOR-FISCAL YR-RECALLED',
 'ASSISTANT PROFESSOR-HCOMP',
 'RESEARCH PROFESSOR',
 'VST ASST PROFESSOR-ACADEMIC YR',
 'ADJUNCT PROFESSOR-ACADEMIC YR',
 'ADJUNCT PROFESSOR - FISCAL YR',
 'PROFESSOR IN RESIDENCE - FY',
 'VISITING PROFESSOR-ACADEMIC YR',
 'VIS ASST PROFESSOR-MEDCOMP',
 'VSTG PROF-AY-1/9-BUS/ECON/ENGR',
 'ASSOC ADJUNCT PROFESSOR - AY',
 'PROFESSOR - FY -BUS/ECON/ENG',
 'ASSOC ADJUNCT PROFESSOR - FY',
 'ASSOC ADJUNCT PROF-GENCOMP-B',
 'HS ASSOC CLIN PROF-MEDCOMP-A',
 'ASST PROFESSOR - FISCAL YEAR',
 'HS CLIN PROF RECALLED-FY',
 'ASST ADJUNCT PROFESSOR - FY',
 'ADJUNCT PROFESSOR-HCOMP',
 'VISITING PROFESSOR-HCOMP',
 'ASSOCIATE PROFESSOR--SFT-VM',
 'ASST PROF IN RES-MEDCOMP-A',
 'ASST ADJUNCT PROFESSOR-ACAD YR',
 'PROFESSOR IN RESIDENCE-ACAD YR',
 'ASST ADJUNCT PROF-ACAD YR-1/9',
 'PROFESSOR EMERITUS (W/O SAL)',
 'TECHNICAL PROJECT MGT PROF"L 3',
 'ASST ADJ PROF-AY-BUS/ECON/ENG',
 'UNIVERSITY PROFESSOR',
 'PROFESSOR-MEDCOMP-A',
 'VST ASSOC PROFESSOR-AY-1/9TH',
 'VISITING ASSOCIATE PROF-HCOMP',
 'HS ASST CLIN PROFESSOR-ACAD YR',
 'ASSOC PROFESSOR - FISCAL YR',
 'HS ASSOC CLIN PROF-ACAD YR',
 'PROFESSOR-SFT-VM',
 'VST ASSOC PROFESSOR-ACAD YR',
 'VIS ASSOC PROFESSOR-GENCOMP',
 'REGENTS" PROFESSOR',
 'HS ASST CLIN PROF-FY-GENCOMP',
 'VISITING PROFESSOR - FISCAL YR',
 'VST PROFESSOR-ACAD YR-1/9 PMT',
 'ADJ PROF-ACAD YR-BUS/ECON/ENG',
 'PROF IN RES-MEDCOMP-A',
 'ASSOC PROFESSOR-AY-RECALLED',
 'VST ASSOC PROFESSOR-FISCAL YR',
 'CLINICAL PROFESSOR-VOLUNTEER',
 'ASST ADJ PROF-FY-BUS/ECON/ENG',
 'ASOC ADJUNCT PROF-GENCOMP-B',
 'ASSOC PROF-FY-BUS/ECON/ENG',
 'MGT AND PROF PROG (UNTITLED)',
 'AST PROF OF CLIN____-MEDCOMP-A',
 'ASST ADJUNCT PROF-GENCOMP-B',
 'TECHNICAL PROJECT MGT PROF"L 2',
 'ASST PROF IN RESIDENCE-ACAD YR',
 'ASSOC CLINICAL PROFESSOR-VOL',
 'HS CLINICAL PROFESSOR-ACAD YR',
 'ADJUNCT PROFESSOR-ACAD YR-1/9',
 'VST PROFESSOR-LAW SCHOOL SCALE',
 'TECHNICAL PROJECT MGT PROF"L 4',
 'PROFESSOR OF CLINICAL___',
 'ASSOC PROF IN RES-MEDCOMP-A',
 'ADJUNCT PROF-MEDCOMP-B',
 'PROF-AY-1/9-BUS/ECON/ENG-RECAL',
 'ASST PROF IN RES-GENCOMP-B',
 'ASSOC PROF IN RES-GENCOMP-B',
 'ASST ADJUNCT PROF-FY-GENCOMP',
 'PROF IN RES-GENCOMP-B',
 'ASO PROF OF CLIN___-MEDCOMP-A',
 'ASSOC PROF-RECALLED-AY-1/9TH',
 'PROF OF CLIN___-MEDCOMP-A',
 'HS CLIN PROF-MEDCOMP-A',
 'AST PROF OF CLIN___-MEDCOMP-A',
 'PROF IN RES-AY-BUS/ECON/ENG',
 'ASSOC ADJUNCT PROF-ACAD YR-1/9',
 'ACT ASST PROFESSOR-ACADEMIC YR',
 'CHIEF ADM & PROF SERVS OFFICER',
 'PROF-AY-BUS/ECON/ENG-RECALLED',
 'ADJ PROF-AY-1/9-BUS/ECON/ENG',
 'ASSOC PROF IN RESIDENCE-SFT-VM',
 'ASSISTANT PROFESSOR-FY-GENCOMP',
 'ASST PROF-FY-BUS/ECON/ENG',
 'ACT AST PROF-AY-BUS/ECON/ENG',
 'VIS ASSOC PROFESSOR-MEDCOMP',
 'AST PROF OF CLIN____-GENCOMP-A',
 'ASSISTANT PROFESSOR-AY-1/9TH',
 'ASSOC PROF IN RESIDENCE- FY',
 'ACT ASSOC PROFESSOR-ACAD YR',
 'ADJUNCT PROF-GENCOMP-B',
 'RES PROF-MILLER INST -ACAD YR',
 'ADJUNCT PROF-MEDCOMP-A',
 'ASST ADJUNCT PROF-MEDCOMP-B',
 'ASSOC PROFESSOR-FY-RECALL',
 'ASSO ADJ PROF-AY-BUS/ECON/ENG',
 'ASSOC ADJUNCT PROF-FY-GENCOMP',
 'PROFESSOR-AY-1/9-BUS/ECON/ENG',
 'ASSISTANT PROFESSOR-MEDCOMP-A',
 'ASST PROF-AY-1/9-BUS/ECON/ENG',
 'ASSOCIATE PROFESSOR-GENCOMP-B',
 'ACTING ASSOC PROFESSOR-HCOMP',
 'ACTING ASST PROFESSOR-HCOMP',
 'ASST PROFESSOR-ACAD YR-RECALL',
 'ACTING PROFESSOR - FISCAL YR',
 'HS ASSOC CLIN PROF-FY-GENCOMP',
 'ASSOC ADJUNCT PROFESSOR-SFT-VM',
 'ASST ADJUNCT PROFESSOR-SFT-VM',
 'ASSOCIATE PROFESSOR-MEDCOMP-A',
 'ACTING PROFESSOR-HCOMP',
 'PROFESSOR-ACAD YR-1/9TH PMT',
 'ADJ PROF-FY-BUS/ECON/ENG',
 'ASSOCIATE PROFESSOR-FY-GENCOMP',
 'ASSOC PROF IN RSDNC-AY-1/9TH',
 'HS ASST CLIN PROF-MEDCOMP-B',
 'ASSOC PROF IN RESIDENCE- AY',
 'ACT PROF-ACAD YR-BUS/ECON/ENG',
 'VSTG PROF-ACAD YR-BUS/ECON/ENG',
 'ASSOCIATE PROFESSOR-GENCOMP-A',
 'ACTING PROFESSOR-ACADEMIC YR',
 'CLIN PROF-DENTISTRY-50%/+ FY',
 'ASSOC ADJUNCT PROF-MEDCOMP-A',
 'ADJUNCT PROFESSOR-SFT-VM',
 'HS ASSOC CLIN PROF-MEDCOMP-B',
 'ACT ASSOC PROF-AY-BUS/ECON/ENG',
 'TECHNICAL PROJECT MGT PROF"L 5',
 'ASSOC PROF IN RES-FY-MEDCOMP',
 'PROFESSOR-LAW SCH SCALE-1/9TH',
 'HS ASSOC CLIN PROF-GENCOMP-B',
 'HS ASST CLIN PROF-FY',
 'ASST ADJ PROF-FY-B/E/E',
 'ASST PROF OF CLIN-FY',
 'ASSOC PROF-AY',
 'HS ASST CLIN PROF-HCOMP',
 'ASST PROF OF CLIN-HCOMP',
 'ASST PROF-AY',
 'ASSOC PROF OF CLIN-HCOMP',
 'VIS ASST PROF',
 'VIS ASST PROF-HCOMP',
 'ASST CLIN PROF-VOL',
 'ASST ADJ PROF-HCOMP',
 'ASST PROF IN RES-HCOMP',
 'ASSOC CLIN PROF-VOL',
 'ASST PROF-HCOMP',
 'PROF EMERITUS(WOS)',
 'PROF IN RES-HCOMP',
 'PROF-AY-B/E/E',
 'PROF-HCOMP',
 'PROF-AY',
 'ASST PROF-AY-B/E/E',
 'HS CLIN PROF-FY',
 'HS ASSOC CLIN PROF-HCOMP',
 'PROF-AY-LAW',
 'PROF OF CLIN-HCOMP',
 'ASSOC PROF-HCOMP',
 'HS CLIN PROF-HCOMP',
 'ASSOC PROF IN RES-HCOMP',
 'ASSOC ADJ PROF-HCOMP',
 'ASST ADJ PROF-AY',
 'PROF-FY',
 'HS ASSOC CLIN PROF-FY',
 'ASSOC PROF OF CLIN-FY',
 'PROF IN RES-FY',
 'PROF OF CLIN-FY',
 'ASSOC PROF-AY-B/E/E',
 'ASST PROF-AY-1/9-B/E/E',
 'ADJ PROF-HCOMP',
 'ADJ PROF-AY',
 'ADJ PROF-FY',
 'ASSOC ADJ PROF-AY',
 'ACT ASST PROF-FY',
 'PROF-FY-B/E/E',
 'VIS PROF',
 'ASSOC ADJ PROF-FY',
 'ASST PROF-SFT-VM',
 'ASSOC PROF-FY',
 'ACT PROF-AY-LAW',
 'ASST ADJ PROF-FY',
 'ASSOC PROF-SFT-VM',
 'VIS ASSOC PROF',
 'PROF IN RES-AY',
 'PROF-SFT-VM',
 'ASST ADJ PROF-AY-B/E/E',
 'CLIN PROF-VOL',
 'UNIV PROF',
 'HS ASST CLIN PROF-AY',
 'ASST PROF-AY-1/9',
 'HS ASSOC CLIN PROF-AY',
 'VIS ASSOC PROF-HCOMP',
 'ASST PROF-FY',
 'ADJ PROF-AY-B/E/E',
 'ASSOC PROF-FY-B/E/E',
 'VIS PROF-HCOMP',
 'ADJ PROF-AY-1/9',
 'ACT ASSOC PROF-HCOMP',
 'HS CLIN PROF-AY',
 'ASSOC PROF IN RES-FY',
 'ADJ PROF-FY-B/E/E',
 'ASSOC PROF IN RES-AY',
 'ACT ASST PROF-AY',
 'ACT ASSOC PROF-AY-B/E/E',
 'ASSOC ADJ PROF-AY-B/E/E',
 'PROF IN RES-AY-B/E/E',
 'PROF-AY-1/9',
 'ASST ADJ PROF-AY-1/9',
 'ASST PROF IN RES-AY',
 'ASSOC PROF IN RES-SFT-VM',
 'ASST PROF-FY-B/E/E',
 'ACT ASST PROF-HCOMP',
 'RES PROF-MILLER INST-AY',
 'ASSOC ADJ PROF-AY-1/9',
 'ASSOC PROF IN RES-AY-B/E/E',
 'REGENTS" PROF',
 'ACT PROF-HCOMP',
 'ASST PROF IN RES-FY',
 'ASSOC ADJ PROF-FY-B/E/E',
 'ADJ PROF-AY-1/9-B/E/E',
 'ASSOC PROF-AY-1/9',
 'ASST ADJ PROF-SFT-VM',
 'ASST PROF IN RES-AY-B/E/E',
 'ACT ASSOC PROF-AY',
 'ASSOC ADJ PROF-AY-1/9-B/E/E',
 'ASST ADJ PROF-AY-1/9-B/E/E',
 'PROF-AY-1/9-B/E/E',
 'ACT PROF-AY',
 'CLIN PROF-DENT-50%/+-FY',
 'ADJ PROF-SFT-VM',
 'ACT ASSOC PROF-FY',
 'VSTG PROF-ACAD YR-BUS/ENG',
 'PROF-AY-1/9-BUS/ENG-RECALLED',
 'ASST PROF IN RES-SFT-VM',
 'PROF-ACAD YR-BUS/ENG-RECALLED',
 'ACT ASST PROF-AY-B/E/E',
 'PROFESSOR-FY-GENCOMP',
 'PROF IN RES-SFT-VM',
 'REGENTS\\ PROF',
 'PROF IN RES-AY-1/9',
 'ACT ASSOC PROF-AY-1/9-B/E/E',
 'ASSOC PROF-AY-1/9-B/E/E',
 'HEALTH PROFNS EDUC SPEC 2',
 'HEALTH PROFNS EDUC SPEC 4',
 'HEALTH PROFNS EDUC SPEC 3',
 'ASSOC ADJ PROF-SFT-VM',
 'HEALTH PROFNS EDUC MGR 2',
 'HEALTH PROFNS EDUC SUPV 2',
 'HEALTH PROFNS EDUC SPEC 4 GF',
 'HEALTH PROFNS EDUC MGR 1',
 'HEALTH PROFNS EDUC MGR 3',
 'HEALTH PROFNS EDUC SPEC 3 GF',
 'HEALTH PROFNS EDUC SPEC 5',
 'HEALTH PROFNS EDUC SUPV 1',
 'ADJ PROF-AY-1/10-BEE',
 'ADJUNCT PROF-GENCOMP-A',
 'ACT PROF-FY',
 'ADJ. PROF',
 'PROF OF CLIN-SFT-VM',
 'ASSOC. PROF OF LAW',
 'PROF OF LAW',
 'ASSOC DIR (PROF)',
 'ASST PROF OF CLIN-SFT-VM',
 'VTG ASST PROF OF LAW',
 'VTG PROF OF LAW',
 'ASSOC PROF OF CLIN-SFT-VM',
 'HS CLIN PROF-SFT-VM',
 'CLIN PROF OF LAW',
 'PROFESSOR (NON-TENURE)',
 'HS ASST CLIN PROF-SFT-VM',
 "REGENTS' PROF",
 'HS ASSOC CLIN PROF-SFT-VM',
 'ACT PROF-AY-B/E/E',
 'ASSOC ADJ PROF-AY-1/10',
 'SULLIVAN PROF OF LAW',
 'ACT ASST PROF-AY-1/9-B/E/E',
 'RECALLED PROF OF LAW',
 'ACT ASSOC PROF-SFT-VM',
 'ADJUNCT PROFESSOR',
 'ASSOCIATE PROFESSOR OF LAW',
 'CLINICAL PROFESSOR OF LAW',
 'PROFESSOR OF LAW',
 'ASSOCIATE DIRECTOR (PROF)',
 'VISITING PROFESSOR OF LAW',
 'SULLIVAN PROFESSOR OF LAW',
 'ASST PROF IN RES-AY-1/9',
 'PROFESSOR OF LAW (NON-TENURE)',
 'RECALLED PROFESSOR OF LAW']

In [86]:
def title_assign(x):
    if "PROFL" in x or "PROFESSIONAL" in x:
        return "OTHER"
    elif "VST" in x and "ASST" in x:
        return "VST ASST"
    elif "VST" in x and "ASSOC" in x:
        return "VST ASSOC"
    elif "VST" in x:
        return "VST PROF"
    elif "ADJ" in x and "ASST" in x:
        return "ADJ ASST"
    elif ("ASOC" in x or "ASSOC" in x) and "ADJ" in x:
        return "ADJ ASOC"
    elif "ADJ" in x:
        return "ADJ PROF"
    elif ("ASST" in x or "ASSIST" in x) and "PROF" in x:
        return "ASST PROF"
    elif "ASSOC" in x and "PROF" in x:
        return "ASSOC PROF"
    elif "PROF" in x:
        return "PROF"
    elif "SR" in x and "LECT" in x:
        return "SR LECT"
    elif "LECT" in x:
        return "LECT"
    else:
        return "OTHER"

In [87]:
prof_rows["title"] = prof_rows["title"].apply(title_assign)

/var/folders/py/yn4jz9f166sd76n0j33k5ny00000gn/T/ipykernel_30120/1405741927.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prof_rows["title"] = prof_rows["title"].apply(title_assign)

In [88]:
prof_rows[prof_rows["title"]!="OTHER"]

,row_names,id,year,location,first.name,last.name,title,gross.pay,regular.pay,overtime.pay,other.pay
0,1,1,2010,Santa Cruz,*****,*****,ASST PROF,74511.10,69999.96,0.0,4511.14
20,21,21,2010,Berkeley,***********,***********,LECT,30364.71,25454.75,0.0,4909.96
94,95,95,2010,Berkeley,***********,***********,LECT,29248.46,29248.46,0.0,0.00
175,176,176,2010,Berkeley,***********,***********,LECT,27258.69,27058.69,0.0,200.00
178,179,179,2010,Berkeley,***********,***********,LECT,28679.78,28679.78,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...
3024446,3024447,210073,2020,Los Angeles,ALEXANDER,MAZZAFERRO,ASST PROF,39417.00,39417.00,0.0,0.00
3024450,3024451,210077,2020,San Diego,WILLIAM,MAZZEI,PROF,218546.00,163606.00,0.0,54940.00
3024455,3024456,210082,2020,Los Angeles,JOHN,MAZZIOTTA,PROF,1035172.00,695172.00,0.0,340000.00
3024456,3024457,210083,2020,Los Angeles,MAURIZIO,MAZZOCCO,ASSOC PROF,283000.00,283000.00,0.0,0.00
3024465,3024466,210092,2020,Berkeley,MASSIMO,MAZZOTTI,PROF,141858.00,141858.00,0.0,0.00

In [89]:
prof_rows.groupby("title")["gross.pay"].mean().sort_values()

title
VST ASSOC      18720.152473
VST ASST       20629.142353
VST PROF       28685.205937
LECT           32005.976347
ADJ ASST       83534.351612
ADJ ASOC       97817.998927
ADJ PROF       98626.052368
SR LECT       118420.398696
ASST PROF     150323.815197
ASSOC PROF    171999.885210
PROF          217624.153142
Name: gross.pay, dtype: float64

In [64]:
prof_rows.groupby("location")["gross.pay"].mean().sort_values()

location
UCOP                        20223.674186
DANR                        25276.898667
Hastings                    61655.841121
Hastings College Of Law     62853.018868
Merced                     113714.270824
Riverside                  118308.432540
Santa Cruz                 123314.845434
Santa Barbara              141446.017037
Berkeley                   150359.078108
Davis                      172797.047093
Irvine                     177607.196310
San Diego                  197651.592376
San Francisco              207881.533423
Los Angeles                209347.684015
Name: gross.pay, dtype: float64

In [71]:
np.isin(prof_rows["title"],["PROF"])

array([False,  True, False, ...,  True, False,  True])

In [82]:
pd.DataFrame(prof_rows.groupby(["year","title"])["gross.pay"].mean())

                     gross.pay
year title
2010 ADJ ASOC     95952.950491
     ADJ ASST     38646.620972
     ADJ PROF     96407.767079
     ASSOC PROF  138597.745982
     ASST PROF   126382.080895
...                        ...
2020 ADJ PROF     96265.327338
     ASSOC PROF  214972.863824
     ASST PROF   179259.301004
     PROF        269055.442667
     VST ASSOC    12444.000000

[96 rows x 1 columns]

In [79]:
prof_rows[np.isin(prof_rows['first.name'],["FREDERIC"])]

,row_names,id,year,location,first.name,last.name,title,gross.pay,regular.pay,overtime.pay,other.pay
879385,879386,105396,2013,San Francisco,FREDERIC,AMBROGGI,ADJ ASST,29750.0,29750.0,0.0,0.0
1151183,1151184,108752,2014,San Francisco,FREDERIC,AMBROGGI,ADJ ASST,81150.0,77069.0,0.0,4081.0
1297543,1297544,255112,2014,Berkeley,FREDERIC,THEUNISSEN,PROF,157760.0,118558.0,0.0,39202.0
1427704,1427705,110017,2015,San Francisco,FREDERIC,AMBROGGI,ADJ ASST,68361.0,49586.0,0.0,18775.0
1578497,1578498,260810,2015,Berkeley,FREDERIC,THEUNISSEN,PROF,163924.0,121323.0,0.0,42601.0
1868897,1868898,269696,2016,Berkeley,FREDERIC,THEUNISSEN,PROF,177105.0,137843.0,0.0,39262.0
1874686,1874687,275485,2016,San Francisco,FREDERIC,VAN GOOL,ADJ ASST,86488.0,86488.0,0.0,0.0
2065236,2065237,174894,2017,Los Angeles,FREDERIC,GRILLOT,PROF,22665.0,22665.0,0.0,0.0
2166451,2166452,276109,2017,Berkeley,FREDERIC,THEUNISSEN,PROF,165819.0,147075.0,0.0,18744.0
2172396,2172397,282054,2017,San Francisco,FREDERIC,VAN GOOL,ADJ ASST,90183.0,90183.0,0.0,0.0
2371322,2371323,182910,2018,Los Angeles,FREDERIC,GRILLOT,PROF,4574.0,4574.0,0.0,0.0
2435822,2435823,247410,2018,Los Angeles,FREDERIC,PAIK SCHOENBERG,PROF,289591.0,173417.0,0.0,116174.0
2475972,2475973,287560,2018,Berkeley,FREDERIC,THEUNISSEN,PROF,169218.0,149778.0,0.0,19440.0
2482163,2482164,293751,2018,San Francisco,FREDERIC,VAN GOOL,ADJ ASST,99958.0,94958.0,0.0,5000.0
2646483,2646484,147778,2019,Davis,FREDERIC,CHEDIN,PROF,179038.0,142184.0,0.0,36854.0
2678072,2678073,179367,2019,Santa Barbara,FREDERIC,GIBOU,PROF,225583.0,153467.0,0.0,72116.0
2749520,2749521,250815,2019,Los Angeles,FREDERIC,PAIK SCHOENBERG,PROF,283826.0,177933.0,0.0,105893.0
2790846,2790847,292141,2019,Berkeley,FREDERIC,THEUNISSEN,PROF,158233.0,156983.0,0.0,1250.0
2794428,2794429,295723,2019,Davis,FREDERIC,TROY II,PROF,12553.0,0.0,0.0,12553.0
2797294,2797295,298589,2019,San Francisco,FREDERIC,VAN GOOL,ADJ ASST,118370.0,101767.0,0.0,16603.0
2941311,2941312,126938,2020,Davis,FREDERIC,CHEDIN,PROF,163778.0,147400.0,0.0,16378.0
2972931,2972932,158558,2020,Santa Barbara,FREDERIC,GIBOU,PROF,235089.0,160300.0,0.0,74789.0
2982444,2982445,168071,2020,San Diego,FREDERIC,HARRIS,ADJ PROF,34923.0,31923.0,0.0,3000.0
3003001,3003002,188628,2020,San Diego,FREDERIC,KOLB,PROF,406294.0,201800.0,0.0,204494.0